/**
 *  Table 0 - National/International Originating Centers
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/on388/table0.html)
 * @param code
 */
export const lookupTable0: Record<number, string> = {
  1: 'Melbourne (WMC)',
  2: 'Melbourne (WMC)',
  3: 'Melbourne (WMC)',
  4: 'Moscow (WMC)',
  5: 'Moscow (WMC)',
  6: 'Moscow (WMC)',
  7: 'US National Weather Service - NCEP (WMC)',
  8: 'US National Weather Service - NWSTG (WMC)',
  9: 'US National Weather Service - Other (WMC)',
  10: 'Cairo (RSMC/RAFC)',
  11: 'Cairo (RSMC/RAFC)',
  12: 'Dakar (RSMC/RAFC)',
  13: 'Dakar (RSMC/RAFC)',
  14: 'Nairobi (RSMC/RAFC)',
  15: 'Nairobi (RSMC/RAFC)',
  16: 'Casablanca (RSMC)',
  17: 'Tunis (RSMC)',
  18: 'Tunis-Casablanca (RSMC)',
  19: 'Tunis-Casablanca (RSMC)',
  20: 'Las Palmas (RAFC)',
  21: 'Algiers (RSMC)',
  22: 'ACMAD',
  23: 'Mozambique (NMC)',
  24: 'Pretoria (RSMC)',
  25: 'La Reunion (RSMC)',
  26: 'Khabarovsk (RSMC)',
  27: 'Khabarovsk (RSMC)',
  28: 'New Delhi (RSMC/RAFC)',
  29: 'New Delhi (RSMC/RAFC)',
  30: 'Novosibirsk (RSMC)',
  31: 'Novosibirsk (RSMC)',
  32: 'Tashkent (RSMC)',
  33: 'Jeddah (RSMC)',
  34: 'Tokyo (RSMC), Japanese Meteorological Agency',
  35: 'Tokyo (RSMC), Japanese Meteorological Agency',
  36: 'Bankok',
  37: 'Ulan Bator',
  38: 'Beijing (RSMC)',
  39: 'Beijing (RSMC)',
  40: 'Seoul',
  41: 'Buenos Aires (RSMC/RAFC)',
  42: 'Buenos Aires (RSMC/RAFC)',
  43: 'Brasilia (RSMC/RAFC)',
  44: 'Brasilia (RSMC/RAFC)',
  45: 'Santiago',
  46: 'Brazilian Space Agency - INPE',
  47: 'Columbia (NMC)',
  48: 'Ecuador (NMC)',
  49: 'Peru (NMC)',
  50: 'Venezuela (NMC)',
  51: 'Miami (RSMC/RAFC)',
  52: 'Miami (RSMC), National Hurricane Center',
  53: 'Canadian Meteorological Service - Montreal (RSMC)',
  54: 'Canadian Meteorological Service - Montreal (RSMC)',
  55: 'San Francisco',
  56: 'ARINC Center',
  57: 'US Air Force - Air Force Global Weather Center',
  58: 'Fleet Numerical Meteorology and Oceanography Center,Monterey,CA,USA',
  59: 'The NOAA Forecast Systems Lab, Boulder, CO, USA',
  60: 'National Center for Atmospheric Research (NCAR), Boulder, CO',
  61: 'Service ARGOS - Landover, MD, USA',
  62: 'US Naval Oceanographic Office',
  63: 'International Research Institude for Climate and Society',
  64: 'Honolulu',
  65: 'Darwin (RSMC)',
  66: 'Darwin (RSMC)',
  67: 'Melbourne (RSMC)',
  69: 'Wellington (RSMC/RAFC)',
  70: 'Wellington (RSMC/RAFC)',
  71: 'Nadi (RSMC)',
  72: 'Singapore',
  73: 'Malaysia (NMC)',
  74: 'U.K. Met Office - Exeter (RSMC)',
  75: 'U.K. Met Office - Exeter (RSMC)',
  76: 'Moscow (RSMC/RAFC)',
  78: 'Offenbach (RSMC)',
  79: 'Offenbach (RSMC)',
  80: 'Rome (RSMC)',
  81: 'Rome (RSMC)',
  82: 'Norrkoping',
  83: 'Norrkoping',
  84: 'French Weather Service - Toulouse',
  85: 'French Weather Service - Toulouse',
  86: 'Helsinki',
  87: 'Belgrade',
  88: 'Oslo',
  89: 'Prague',
  90: 'Episkopi',
  91: 'Ankara',
  92: 'Frankfurt/Main (RAFC)',
  93: 'London (WAFC)',
  94: 'Copenhagen',
  95: 'Rota',
  96: 'Athens',
  97: 'European Space Agency (ESA)',
  98: 'European Center for Medium-Range Weather Forecasts (RSMC)',
  99: 'De Bilt, Netherlands',
  100: 'Brazzaville',
  101: 'Abidjan',
  102: 'Libyan Arab Jamahiriya (NMC)',
  103: 'Madagascar (NMC)',
  104: 'Mauritius (NMC)',
  105: 'Niger (NMC)',
  106: 'Seychelles (NMC)',
  107: 'Uganda (NMC)',
  108: 'United Republic of Tanzania (NMC)',
  109: 'Zimbabwe (NMC)',
  110: 'Hong-Kong',
  111: 'Afghanistan (NMC)',
  112: 'Bahrain (NMC)',
  113: 'Bangladesh (NMC)',
  114: 'Bhutan (NMC)',
  115: 'Cambodia (NMC)',
  116: "Democratic People's Republic of Korea (NMC)",
  117: 'Islamic Republic of Iran (NMC)',
  118: 'Iraq (NMC)',
  119: 'Kazakhstan (NMC)',
  120: 'Kuwait (NMC)',
  121: 'Kyrgyz Republic (NMC)',
  122: "Lao People's Democratic Republic (NMC)",
  123: 'Macao, China',
  124: 'Maldives (NMC)',
  125: 'Myanmar (NMC)',
  126: 'Nepal (NMC)',
  127: 'Oman (NMC)',
  128: 'Pakistan (NMC)',
  129: 'Qatar (NMC)',
  130: 'Yemen (NMC)',
  131: 'Sri Lanka (NMC)',
  132: 'Tajikistan (NMC)',
  133: 'Turkmenistan (NMC)',
  134: 'United Arab Emirates (NMC)',
  135: 'Uzbekistan (NMC)',
  136: 'Viet Nam (NMC)',
  140: 'Bolivia (NMC)',
  141: 'Guyana (NMC)',
  142: 'Paraguay (NMC)',
  143: 'Suriname (NMC)',
  144: 'Uruguay (NMC)',
  145: 'French Guyana',
  146: 'Brazilian Navy Hydrographic Center',
  147: 'National Commission on Space Activities - Argentina',
  148: 'Brazilian Department of Airspace Control - DECEA',
  150: 'Antigua and Barbuda (NMC)',
  151: 'Bahamas (NMC)',
  152: 'Barbados (NMC)',
  153: 'Belize (NMC)',
  154: 'British Caribbean Territories Center',
  155: 'San Jose',
  156: 'Cuba (NMC)',
  157: 'Dominica (NMC)',
  158: 'Dominican Republic (NMC)',
  159: 'El Salvador (NMC)',
  160: 'US NOAA/NESDIS',
  161: 'US NOAA Office of Oceanic and Atmospheric Research',
  162: 'Guatemala (NMC)',
  163: 'Haiti (NMC)',
  164: 'Honduras (NMC)',
  165: 'Jamaica (NMC)',
  166: 'Mexico City',
  167: 'Netherlands Antilles and Aruba (NMC)',
  168: 'Nicaragua (NMC)',
  169: 'Panama (NMC)',
  170: 'Saint Lucia (NMC)',
  171: 'Trinidad and Tobago (NMC)',
  172: 'French Departments in RA IV',
  173: 'US National Aeronautics and Space Administration (NASA)',
  174: 'Integrated System Data Management/Marine Environmental Data Service (ISDM/MEDS) - Canada',
  176: 'US Cooperative Institude for Meteorological Satellite Studies',
  190: 'Cook Islands (NMC)',
  191: 'French Polynesia (NMC)',
  192: 'Tonga (NMC)',
  193: 'Vanuatu (NMC)',
  194: 'Brunei (NMC)',
  195: 'Indonesia (NMC)',
  196: 'Kiribati (NMC)',
  197: 'Federated States of Micronesia (NMC)',
  198: 'New Caledonia (NMC)',
  199: 'Niue',
  200: 'Papua New Guinea (NMC)',
  201: 'Philippines (NMC)',
  202: 'Samoa (NMC)',
  203: 'Solomon Islands (NMC)',
  204: 'Narional Institude of Water and Atmospheric Research - New Zealand',
  210: 'Frascati (ESA/ESRIN)',
  211: 'Lanion',
  212: 'Lisbon',
  213: 'Reykjavik',
  214: 'Madrid',
  215: 'Zurich',
  216: 'Service ARGOS - Toulouse',
  217: 'Bratislava',
  218: 'Budapest',
  219: 'Ljubljana',
  220: 'Warsaw',
  221: 'Zagreb',
  222: 'Albania (NMC)',
  223: 'Armenia (NMC)',
  224: 'Austria (NMC)',
  225: 'Azerbaijan (NMC)',
  226: 'Belarus (NMC)',
  227: 'Belgium (NMC)',
  228: 'Bosnia and Herzegovina (NMC)',
  229: 'Bulgaria (NMC)',
  230: 'Cyprus (NMC)',
  231: 'Estonia (NMC)',
  232: 'Georgia (NMC)',
  233: 'Dublin',
  234: 'Israel (NMC)',
  235: 'Jordan (NMC)',
  236: 'Latvia (NMC)',
  237: 'Lebanon (NMC)',
  238: 'Lithuania (NMC)',
  239: 'Luxembourg',
  240: 'Malta (NMC)',
  241: 'Monaco',
  242: 'Romania (NMC)',
  243: 'Syrian Arab Republic (NMC)',
  244: 'The former Yugoslav Republic of Macedonia (NMC)',
  245: 'Ukraine (NMC)',
  246: 'Republic of Moldova (NMC)',
  247: 'Operational Programme for the Exchange of Weather RAdar Information (OPERA) - EUMETNET',
  250: 'COnsortium for Small scale  MOdelling (COSMO)',
  254: 'EUMETSAT Operations Center',
  255: 'Missing Value',
};

/**
 *  Table 0.0 - Discipline of Processed Data
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table0-0.shtml)
 * @param code
 */
export const lookupTable00: Record<number, string> = {
  0: 'Meteorological Products',
  1: 'Hydrological Products',
  2: 'Land Surface Products',
  3: 'Satellite Remote Sensing Products (formerly "Space Products")',
  4: 'Space Weather Products',
  10: 'Oceanographic Products',
};

/**
 *  Table 1.2 - Significance of Reference Time
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table1-2.shtml)
 * @param code
 */
export const lookupTable12: Record<number, string> = {
  0: 'Analysis',
  1: 'Start of Forecast',
  2: 'Verifying Time of Forecast',
  3: 'Observation Time',
  255: 'Missing',
};

/**
 *  Table 1.4 - Type of Data
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table1-4.shtml)
 * @param code
 */
export const lookupTable14: Record<number, string> = {
  0: 'Analysis Products',
  1: 'Forecast Products',
  2: 'Analysis and Forecast Products',
  3: 'Control Forecast Products',
  4: 'Perturbed Forecast Products',
  5: 'Control and Perturbed Forecast Products',
  6: 'Processed Satellite Observations',
  7: 'Processed Radar Observations',
  8: 'Event Probability',
  192: 'Experimental Products',
  255: 'Missing',
};

/**
 *  Table 3.1 - Grid Definition Template Number
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml)
 * @param code
 */
export const lookupTable31: Record<number, string> = {
  0: 'Latitude/Longitude (Also called Equidistant Cylindrical or Plate Caree)',
  1: 'Rotated Latitude/Longitude',
  2: 'Stretched Latitude/Longitude',
  3: 'Rotated and Stretched Latitude/Longitude',
  4: 'Variable Resolution Latitude/longitude',
  5: 'Variable Resolution Rotated Latitude/longitude',
  10: 'Mercator',
  11: 'Reserved',
  12: 'Transverse Mercator',
  13: 'Mercator with modelling subdomains definition',
  20: 'Polar Stereographic Projection (Can be North or South)',
  23: 'Polar Stereographic with modelling subdomains definition',
  30: 'Lambert Conformal (Can be Secant, Tangent, Conical, or Bipolar)',
  31: 'Albers Equal Area',
  32: 'Reserved',
  33: 'Lambert conformal with modelling subdomains definition',
  40: 'Gaussian Latitude/Longitude',
  41: 'Rotated Gaussian Latitude/Longitude',
  42: 'Stretched Gaussian Latitude/Longitude',
  43: 'Rotated and Stretched Gaussian Latitude/Longitude',
  50: 'Spherical Harmonic Coefficients',
  51: 'Rotated Spherical Harmonic Coefficients',
  52: 'Stretched Spherical Harmonic Coefficients',
  53: 'Rotated and Stretched Spherical Harmonic Coefficients',
  60: 'Cubed-Sphere Gnomonic  Validation',
  61: 'Spectral Mercator with modelling subdomains definition',
  62: 'Spectral Polar Stereographic with modelling subdomains definition',
  63: 'Spectral Lambert conformal with modelling subdomains definition',
  90: 'Space View Perspective or Orthographic',
  100: 'Triangular Grid Based on an Icosahedron',
  101: 'General Unstructured Grid',
  110: 'Equatorial Azimuthal Equidistant Projection',
  120: 'Azimuth-Range Projection',
  140: 'Lambert Azimuthal Equal Area Projection',
  204: 'Curvilinear Orthogonal Grids',
  1000: 'Cross Section Grid with Points Equally Spaced on the Horizontal',
  1100: 'Hovmoller Diagram with Points Equally Spaced on the Horizontal',
  1200: 'Time Section Grid',
  32768: 'Rotated Latitude/Longitude(Arakawa Staggered E-Grid)',
  32769: 'Rotated Latitude/Longitude(Arakawa Non-E Staggered Grid)',
  65535: 'Missing',
};

/**
 *  Table 3.2 - Grid Definition Template Number
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-1.shtml)
 * @param code
 */
export const lookupTable32: Record<number, string> = {
  0: 'Earth assumed spherical with radius = 6,367,470.0 m',
  1: 'Earth assumed spherical with radius specified (in m) by data producer',
  2: 'Earth assumed oblate spheriod with size as determined by IAU in 1965 (major axis = 6,378,160.0 m, minor axis = 6,356,775.0 m, f = 1/297.0)',
  3: 'Earth assumed oblate spheriod with major and minor axes specified (in km) by data producer',
  4: 'Earth assumed oblate spheriod as defined in IAG-GRS80 model (major axis = 6,378,137.0 m, minor axis = 6,356,752.314 m, f = 1/298.257222101)',
  5: 'Earth assumed represented by WGS84 (as used by ICAO since 1998) (Uses IAG-GRS80 as a basis)',
  6: 'Earth assumed spherical with radius = 6,371,229.0 m',
  7: 'Earth assumed oblate spheroid with major and minor axes specified (in m) by data producer',
  8: 'Earth model assumed spherical with radius 6,371,200 m, but the horizontal datum of the resulting Latitude/Longitude field is the WGS84 reference frame',
  9: 'Earth represented by the OSGB 1936 Datum, using the Airy_1830 Spheroid, the Greenwich meridian as 0 Longitude, the Newlyn datum as mean sea level, 0 height.',
  255: 'Missing',
};

/**
 *  Table 4.0 - PRODUCT DEFINITION TEMPLATE NUMBER
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-0.shtml)
 * @param code
 */
export const lookupTable40: Record<number, string> = {
  0: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time.',
  1: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time.',
  2: 'Derived forecasts based on all ensemble members at a horizontal level or in a horizontal layer at a point in time.',
  3: 'Derived forecasts based on a cluster of ensemble members over a rectangular area at a horizontal level or in a horizontal layer at a point in time.',
  4: 'Derived forecasts based on a cluster of ensemble members over a circular area at a horizontal level or in a horizontal layer at a point in time.',
  5: 'Probability forecasts at a horizontal level or in a horizontal layer at a point in time.',
  6: 'Percentile forecasts at a horizontal level or in a horizontal layer at a point in time.',
  7: 'Analysis or forecast error at a horizontal level or in a horizontal layer at a point in time.',
  8: 'Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.',
  9: 'Probability forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.',
  10: 'Percentile forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.',
  11: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.',
  12: 'Derived forecasts based on all ensemble members at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.',
  13: 'Derived forecasts based on a cluster of ensemble members over a rectangular area at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.',
  14: 'Derived forecasts based on a cluster of ensemble members over a circular area at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.',
  15: 'Average, accumulation, extreme values or other statistically-processed values over a spatial area at a horizontal level or in a horizontal layer at a point in time.',
  20: 'Radar product',
  30: 'Satellite product   NOTE: This template is deprecated. Template 4.31 should be used instead.',
  31: 'Satellite product',
  32: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for simulate (synthetic) satellite data',
  33: 'Individual Ensemble Forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for simulated (synthetic) satellite data',
  34: 'Individual Ensemble Forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval for simulated (synthetic) satellite data',
  35: 'Satellite product with or without associated quality values',
  40: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents.',
  41: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents.',
  42: 'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents.',
  43: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for atmospheric chemical constituents.',
  44: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.',
  45: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for aerosol.',
  46: 'Average, accumulation, and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for aerosol.',
  47: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval for aerosol.',
  48: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol.',
  49: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol.',
  51: 'Categorical forecast at a horizontal level or in a horizontal layer at a point in time.',
  53: 'Partitioned names at a horizontal level or horizontal layer at a point in time.',
  54: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for partitioned names.',
  55: 'Spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time',
  56: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for spatio-temporal changing tile names.',
  57: 'Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for atmospheric chemical constituents based on a distribution function',
  58: 'Individual Ensemble Forecast, Control and Perturbed, at a horizontal level or in a horizontal layer at a point in time interval for Atmospheric Chemical Constituents based on a distribution function',
  59: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for spatio-temporal changing tile names (corrected version of template 4.56 - See Template 4.59)',
  60: 'Individual Ensemble Reforecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time.',
  61: 'Individual Ensemble Reforecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval',
  62: 'Average, Accumulation and/or Extreme values or other Statistically-processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time',
  63: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles',
  67: 'Average, accumulation and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents based on a distribution function',
  68: 'Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for atmospheric chemical constituents based on a distribution function.',
  70: 'Post-processing analysis or forecast at a horizontal level or in a horizontal layer at a point in time.',
  71: 'Post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time.',
  72: 'Post-processing average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.',
  73: 'Post-processing individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous time interval.',
  91: 'Categorical forecast at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.',
  254: 'CCITT IA5 character string',
  1000: 'Cross-section of analysis and forecast at a point in time.',
  1001: 'Cross-section of averaged or otherwise statistically processed analysis or forecast over a range of time.',
  1002: 'Cross-section of analysis and forecast, averaged or otherwise statistically-processed over latitude or longitude.',
  1100: 'Hovmoller-type grid with no averaging or other statistical processing',
  1101: 'Hovmoller-type grid with averaging or other statistical processing',
  65535: 'Missing',
};

/**
 *  Table 4.1 - name CATEGORY BY PRODUCT DISCIPLINE
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-1.shtml)
 * { [discipline: number]: { [code: number]: string } }
 */
export const lookupTable41: Record<number, Record<number, string>> = {
  0: {
    0: 'Temperature',
    1: 'Moisture',
    2: 'Momentum',
    3: 'Mass',
    4: 'Short-wave radiation',
    5: 'Long-wave radiation',
    6: 'Cloud',
    7: 'Thermodynamic Stability indicies',
    8: 'Kinematic Stability indicies',
    9: 'Temperature Probabilities*',
    10: 'Moisture Probabilities*',
    11: 'Momentum Probabilities*',
    12: 'Mass Probabilities*',
    13: 'Aerosols',
    14: 'Trace gases (e.g. Ozone, CO2)',
    15: 'Radar',
    16: 'Forecast Radar Imagery',
    17: 'Electrodynamics',
    18: 'Nuclear/radiology',
    19: 'Physical atmospheric properties',
    20: 'Atmospheric chemical Constituents',
    190: 'CCITT IA5 string',
    191: 'Miscellaneous',
    192: 'Covariance',
    255: 'Missing',
  },
};

/**
 *  Table 4.2 - name NUMBER BY PRODUCT DISCIPLINE AND name CATEGORY
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2.shtml)
 * { [discipline: number]: { [category: number]: { [code: number]: { name: string, units: string, abbrev: string } } } }
 */
export const lookupTable42: Record<
  number,
  Record<number, Record<number, { name: string; units: string; abbrev: string }>>
> = {
  // Discipline 0
  0: {
    // Category 0
    0: {
      0: { name: 'Temperature', units: 'K', abbrev: 'TMP' },
      1: { name: 'Virtual Temperature', units: 'K', abbrev: 'VTMP' },
      2: { name: 'Potential Temperature', units: 'K', abbrev: 'POT' },
      3: {
        name: 'Pseudo-Adiabatic Potential Temperature (or Equivalent Potential Temperature)',
        units: 'K',
        abbrev: 'EPOT',
      },
      4: { name: 'Maximum Temperature*', units: 'K', abbrev: 'TMAX' },
      5: { name: 'Minimum Temperature*', units: 'K', abbrev: 'TMIN' },
      6: { name: 'Dew Point Temperature', units: 'K', abbrev: 'DPT' },
      7: { name: 'Dew Point Depression (or Deficit)', units: 'K', abbrev: 'DEPR' },
      8: { name: 'Lapse Rate', units: 'K m-1', abbrev: 'LAPR' },
      9: { name: 'Temperature Anomaly', units: 'K', abbrev: 'TMPA' },
      10: { name: 'Latent Heat Net Flux', units: 'W m-2', abbrev: 'LHTFL' },
      11: { name: 'Sensible Heat Net Flux', units: 'W m-2', abbrev: 'SHTFL' },
      12: { name: 'Heat Index', units: 'K', abbrev: 'HEATX' },
      13: { name: 'Wind Chill Factor', units: 'K', abbrev: 'WCF' },
      14: { name: 'Minimum Dew Point Depression*', units: 'K', abbrev: 'MINDPD' },
      15: { name: 'Virtual Potential Temperature', units: 'K', abbrev: 'VPTMP' },
      16: { name: 'Snow Phase Change Heat Flux', units: 'W m-2', abbrev: 'SNOHF' },
      17: { name: 'Skin Temperature', units: 'K', abbrev: 'SKINT' },
      18: { name: 'Snow Temperature (top of snow)', units: 'K', abbrev: 'SNOT' },
      19: {
        name: 'Turbulent Transfer Coefficient for Heat',
        units: 'Numeric',
        abbrev: 'TTCHT',
      },
      20: {
        name: 'Turbulent Diffusion Coefficient for Heat',
        units: 'm2s-1',
        abbrev: 'TDCHT',
      },
      21: { name: 'Apparent Temperature **', units: 'K', abbrev: 'APTMP' },
      22: {
        name: 'Temperature Tendency due to Short-Wave Radiation',
        units: 'K s-1',
        abbrev: 'TTSWR',
      },
      23: {
        name: 'Temperature Tendency due to Long-Wave Radiation',
        units: 'K s-1',
        abbrev: 'TTLWR',
      },
      24: {
        name: 'Temperature Tendency due to Short-Wave Radiation, Clear Sky',
        units: 'K s-1',
        abbrev: 'TTSWRCS',
      },
      25: {
        name: 'Temperature Tendency due to Long-Wave Radiation, Clear Sky',
        units: 'K s-1',
        abbrev: 'TTLWRCS',
      },
      26: {
        name: 'Temperature Tendency due to nameizations',
        units: 'K s-1',
        abbrev: 'TTPARM',
      },
      27: { name: 'Wet Bulb Temperature', units: 'K', abbrev: 'WETBT' },
      28: { name: 'Unbalanced Component of Temperature', units: 'K', abbrev: 'UCTMP' },
      29: { name: 'Temperature Advection', units: 'K s-1', abbrev: 'TMPADV' },
      192: { name: 'Snow Phase Change Heat Flux', units: 'W m-2', abbrev: 'SNOHF' },
      193: {
        name: 'Temperature Tendency by All Radiation',
        units: 'K s-1',
        abbrev: 'TTRAD',
      },
      194: { name: 'Relative Error Variance', units: '', abbrev: 'REV' },
      195: {
        name: 'Large Scale Condensate Heating Rate',
        units: 'K s-1',
        abbrev: 'LRGHR',
      },
      196: { name: 'Deep Convective Heating Rate', units: 'K s-1', abbrev: 'CNVHR' },
      197: {
        name: 'Total Downward Heat Flux at Surface',
        units: 'W m-2',
        abbrev: 'THFLX',
      },
      198: {
        name: 'Temperature Tendency by All Physics',
        units: 'K s-1',
        abbrev: 'TTDIA',
      },
      199: {
        name: 'Temperature Tendency by Non-radiation Physics',
        units: 'K s-1',
        abbrev: 'TTPHY',
      },
      200: {
        name: 'Standard Dev. of IR Temp. over 1x1 deg. area',
        units: 'K',
        abbrev: 'TSD1D',
      },
      201: { name: 'Shallow Convective Heating Rate', units: 'K s-1', abbrev: 'SHAHR' },
      202: { name: 'Vertical Diffusion Heating rate', units: 'K s-1', abbrev: 'VDFHR' },
      203: {
        name: 'Potential Temperature at Top of Viscous Sublayer',
        units: 'K',
        abbrev: 'THZ0',
      },
      204: { name: 'Tropical Cyclone Heat Potential', units: 'Jm-2K', abbrev: 'TCHP' },
      205: { name: 'Effective Layer (EL) Temperature', units: 'C', abbrev: 'ELMELT' },
      255: { name: 'Missing', units: '', abbrev: '' },
    },

    // Category 2
    2: {
      0: { name: 'Wind Direction (from which blowing)', units: '°', abbrev: 'WDIR' },
      1: { name: 'Wind Speed', units: 'm s-1', abbrev: 'WIND' },
      2: { name: 'U-Component of Wind', units: 'm s-1', abbrev: 'UGRD' },
      3: { name: 'V-Component of Wind', units: 'm s-1', abbrev: 'VGRD' },
      4: { name: 'Stream Function', units: 'm2 s-1', abbrev: 'STRM' },
      5: { name: 'Velocity Potential', units: 'm2 s-1', abbrev: 'VPOT' },
      6: { name: 'Montgomery Stream Function', units: 'm2 s-2', abbrev: 'MNTSF' },
      7: { name: 'Sigma Coordinate Vertical Velocity', units: 's-1', abbrev: 'SGCVV' },
      8: { name: 'Vertical Velocity (Pressure)', units: 'Pa s-1', abbrev: 'VVEL' },
      9: { name: 'Vertical Velocity (Geometric)', units: 'm s-1', abbrev: 'DZDT' },
      10: { name: 'Absolute Vorticity', units: 's-1', abbrev: 'ABSV' },
      11: { name: 'Absolute Divergence', units: 's-1', abbrev: 'ABSD' },
      12: { name: 'Relative Vorticity', units: 's-1', abbrev: 'RELV' },
      13: { name: 'Relative Divergence', units: 's-1', abbrev: 'RELD' },
      14: { name: 'Potential Vorticity', units: 'K m2 kg-1 s-1', abbrev: 'PVORT' },
      15: { name: 'Vertical U-Component Shear', units: 's-1', abbrev: 'VUCSH' },
      16: { name: 'Vertical V-Component Shear', units: 's-1', abbrev: 'VVCSH' },
      17: { name: 'Momentum Flux, U-Component', units: 'N m-2', abbrev: 'UFLX' },
      18: { name: 'Momentum Flux, V-Component', units: 'N m-2', abbrev: 'VFLX' },
      19: { name: 'Wind Mixing Energy', units: 'J', abbrev: 'WMIXE' },
      20: { name: 'Boundary Layer Dissipation', units: 'W m-2', abbrev: 'BLYDP' },
      21: { name: 'Maximum Wind Speed *', units: 'm s-1', abbrev: 'MAXGUST' },
      22: { name: 'Wind Speed (Gust)', units: 'm s-1', abbrev: 'GUST' },
      23: { name: 'U-Component of Wind (Gust)', units: 'm s-1', abbrev: 'UGUST' },
      24: { name: 'V-Component of Wind (Gust)', units: 'm s-1', abbrev: 'VGUST' },
      25: { name: 'Vertical Speed Shear', units: 's-1', abbrev: 'VWSH' },
      26: { name: 'Horizontal Momentum Flux', units: 'N m-2', abbrev: 'MFLX' },
      27: { name: 'U-Component Storm Motion', units: 'm s-1', abbrev: 'USTM' },
      28: { name: 'V-Component Storm Motion', units: 'm s-1', abbrev: 'VSTM' },
      29: { name: 'Drag Coefficient', units: 'Numeric', abbrev: 'CD' },
      30: { name: 'Frictional Velocity', units: 'm s-1', abbrev: 'FRICV' },
      31: {
        name: 'Turbulent Diffusion Coefficient for Momentum',
        units: 'm2 s-1',
        abbrev: 'TDCMOM',
      },
      32: { name: 'Eta Coordinate Vertical Velocity', units: 's-1', abbrev: 'ETACVV' },
      33: { name: 'Wind Fetch', units: 'm', abbrev: 'WINDF' },
      34: { name: 'Normal Wind Component **', units: 'm s-1', abbrev: 'NWIND' },
      35: { name: 'Tangential Wind Component **', units: 'm s-1', abbrev: 'TWIND' },
      36: {
        name: 'Amplitude Function for Rossby Wave Envelope for Meridional Wind ***',
        units: 'm s-1',
        abbrev: 'AFRWE',
      },
      37: {
        name: 'Northward Turbulent Surface Stress ****',
        units: 'N m-2 s',
        abbrev: 'NTSS',
      },
      38: {
        name: 'Eastward Turbulent Surface Stress ****',
        units: 'N m-2 s',
        abbrev: 'ETSS',
      },
      39: {
        name: 'Eastward Wind Tendency Due to nameizations',
        units: 'm s-2',
        abbrev: 'EWTPARM',
      },
      40: {
        name: 'Northward Wind Tendency Due to nameizations',
        units: 'm s-2',
        abbrev: 'NWTPARM',
      },
      41: { name: 'U-Component of Geostrophic Wind', units: 'm s-1', abbrev: 'UGWIND' },
      42: { name: 'V-Component of Geostrophic Wind', units: 'm s-1', abbrev: 'VGWIND' },
      43: { name: 'Geostrophic Wind Direction', units: '°', abbrev: 'GEOWD' },
      44: { name: 'Geostrophic Wind Speed', units: 'm s-1', abbrev: 'GEOWS' },
      45: { name: 'Unbalanced Component of Divergence', units: 's-1', abbrev: 'UNDIV' },
      46: { name: 'Vorticity Advection', units: 's-2', abbrev: 'VORTADV' },
      192: { name: 'Vertical Speed Shear', units: 's-1', abbrev: 'VWSH' },
      193: { name: 'Horizontal Momentum Flux', units: 'N m-2', abbrev: 'MFLX' },
      194: { name: 'U-Component Storm Motion', units: 'm s-1', abbrev: 'USTM' },
      195: { name: 'V-Component Storm Motion', units: 'm s-1', abbrev: 'VSTM' },
      196: { name: 'Drag Coefficient', units: 'non-dim', abbrev: 'CD' },
      197: { name: 'Frictional Velocity', units: 'm s-1', abbrev: 'FRICV' },
      198: {
        name: 'Latitude of U Wind Component of Velocity',
        units: 'deg',
        abbrev: 'LAUV',
      },
      199: {
        name: 'Longitude of U Wind Component of  Velocity',
        units: 'deg',
        abbrev: 'LOUV',
      },
      200: {
        name: 'Latitude of V Wind Component of Velocity',
        units: 'deg',
        abbrev: 'LAVV',
      },
      201: {
        name: 'Longitude of V Wind Component of Velocity',
        units: 'deg',
        abbrev: 'LOVV',
      },
      202: { name: 'Latitude of Presure Point', units: 'deg', abbrev: 'LAPP' },
      203: { name: 'Longitude of Presure Point', units: 'deg', abbrev: 'LOPP' },
      204: {
        name: 'Vertical Eddy Diffusivity Heat exchange',
        units: 'm2 s-1',
        abbrev: 'VEDH',
      },
      205: {
        name: 'Covariance between Meridional and Zonal Components of the wind.',
        units: 'm2 s-2',
        abbrev: 'COVMZ',
      },
      206: {
        name: 'Covariance between Temperature and Zonal Components of the wind.',
        units: 'K*m s-1',
        abbrev: 'COVTZ',
      },
      207: {
        name: 'Covariance between Temperature and Meridional Components of the wind.',
        units: 'K*m s-1',
        abbrev: 'COVTM',
      },
      208: {
        name: 'Vertical Diffusion Zonal Acceleration',
        units: 'm s-2',
        abbrev: 'VDFUA',
      },
      209: {
        name: 'Vertical Diffusion Meridional Acceleration',
        units: 'm s-2',
        abbrev: 'VDFVA',
      },
      210: {
        name: 'Gravity wave drag zonal acceleration',
        units: 'm s-2',
        abbrev: 'GWDU',
      },
      211: {
        name: 'Gravity wave drag meridional acceleration',
        units: 'm s-2',
        abbrev: 'GWDV',
      },
      212: {
        name: 'Convective zonal momentum mixing acceleration',
        units: 'm s-2',
        abbrev: 'CNVU',
      },
      213: {
        name: 'Convective meridional momentum mixing acceleration',
        units: 'm s-2',
        abbrev: 'CNVV',
      },
      214: { name: 'Tendency of vertical velocity', units: 'm s-2', abbrev: 'WTEND' },
      215: { name: 'Omega (Dp/Dt) divide by density', units: 'K', abbrev: 'OMGALF' },
      216: {
        name: 'Convective Gravity wave drag zonal acceleration',
        units: 'm s-2',
        abbrev: 'CNGWDU',
      },
      217: {
        name: 'Convective Gravity wave drag meridional acceleration',
        units: 'm s-2',
        abbrev: 'CNGWDV',
      },
      218: { name: 'Velocity Point Model Surface', units: '', abbrev: 'LMV' },
      219: {
        name: 'Potential Vorticity (Mass-Weighted)',
        units: '1/s/m',
        abbrev: 'PVMWW',
      },
      220: {
        name: 'Hourly Maximum of Upward Vertical Velocity',
        units: 'm s-1',
        abbrev: 'MAXUVV',
      },
      221: {
        name: 'Hourly Maximum of Downward Vertical Velocity',
        units: 'm s-1',
        abbrev: 'MAXDVV',
      },
      222: {
        name: 'U Component of Hourly Maximum 10m Wind Speed',
        units: 'm s-1',
        abbrev: 'MAXUW',
      },
      223: {
        name: 'V Component of Hourly Maximum 10m Wind Speed',
        units: 'm s-1',
        abbrev: 'MAXVW',
      },
      224: { name: 'Ventilation Rate', units: 'm2 s-1', abbrev: 'VRATE' },
      225: { name: 'Transport Wind Speed', units: 'm s-1', abbrev: 'TRWSPD' },
      226: { name: 'Transport Wind Direction', units: 'Deg', abbrev: 'TRWDIR' },
      227: {
        name: 'Earliest Reasonable Arrival Time (10% exceedance)',
        units: 's',
        abbrev: 'TOA10',
      },
      228: {
        name: 'Most Likely Arrival Time (50% exceedance)',
        units: 's',
        abbrev: 'TOA50',
      },
      229: {
        name: 'Most Likely Departure Time (50% exceedance)',
        units: 's',
        abbrev: 'TOD50',
      },
      230: {
        name: 'Latest Reasonable Departure Time (90% exceedance)',
        units: 's',
        abbrev: 'TOD90',
      },
      231: { name: 'Tropical Wind Direction', units: '°', abbrev: 'TPWDIR' },
      232: { name: 'Tropical Wind Speed', units: 'm s-1', abbrev: 'TPWSPD' },
      233: {
        name: 'Inflow Based (ESFC) to 50% EL Shear Magnitude',
        units: 'kt',
        abbrev: 'ESHR',
      },
      234: {
        name: 'U Component Inflow Based to 50% EL Shear Vector',
        units: 'kt',
        abbrev: 'UESH',
      },
      235: {
        name: 'V Component Inflow Based to 50% EL Shear Vector',
        units: 'kt',
        abbrev: 'VESH',
      },
      236: {
        name: 'U Component Bunkers Effective Right Motion',
        units: 'kt',
        abbrev: 'UEID',
      },
      237: {
        name: 'V Component Bunkers Effective Right Motion',
        units: 'kt',
        abbrev: 'VEID',
      },
      255: { name: 'Missing', units: '', abbrev: '' },
    },
  },
};

/**
 *  Table 4.3 - TYPE OF GENERATING PROCESS
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-3.shtml)
 * @param code
 */
export const lookupTable43: Record<number, string> = {
  0: 'Analysis',
  1: 'Initialization',
  2: 'Forecast',
  3: 'Bias Corrected Forecast',
  4: 'Ensemble Forecast',
  5: 'Probability Forecast',
  6: 'Forecast Error',
  7: 'Analysis Error',
  8: 'Observation',
  9: 'Climatological',
  10: 'Probability-Weighted Forecast',
  11: 'Bias-Corrected Ensemble Forecast',
  12: 'Post-processed Analysis (See Note)',
  13: 'Post-processed Forecast (See Note)',
  14: 'Nowcast',
  15: 'Hindcast',
  16: 'Physical Retrieval',
  17: 'Regression Analysis',
  18: 'Difference Between Two Forecasts',
  192: 'Forecast Confidence Indicator',
  193: 'Probability-matched Mean',
  194: 'Neighborhood Probability',
  195: 'Bias-Corrected and Downscaled Ensemble Forecast',
  196: 'Perturbed Analysis for Ensemble Initialization',
  197: 'Ensemble Agreement Scale Probability',
  198: 'Post-Processed Deterministic-Expert-Weighted Forecast',
  199: 'Ensemble Forecast Based on Counting',
  200: 'Local Probability-matched Mean',
  255: 'Missing',
};

/**
 *  Table 4.4 - INDICATOR OF UNIT OF TIME RANGE
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-4.shtml)
 * @param code
 */
export const lookupTable44: Record<number, string> = {
  0: 'Minute',
  1: 'Hour',
  2: 'Day',
  3: 'Month',
  4: 'Year',
  5: 'Decade (10 Years)',
  6: 'Normal (30 Years)',
  7: 'Century (100 Years)',
  10: '3 Hours',
  11: '6 Hours',
  12: '12 Hours',
  13: 'Second',
  255: 'Missing',
};

/**
 *  Table 4.5 - FIXED SURFACE TYPES AND UNITS
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-5.shtml)
 * @param code
 */
export const lookupTable45: { [code: number]: { name: string; units: string | null } } = {
  1: { name: 'Ground or Water Surface', units: null },
  2: { name: 'Cloud Base Level', units: null },
  3: { name: 'Level of Cloud Tops', units: null },
  4: { name: 'Level of 0o C Isotherm', units: null },
  5: { name: 'Level of Adiabatic Condensation Lifted from the Surface', units: null },
  6: { name: 'Maximum Wind Level', units: null },
  7: { name: 'Tropopause', units: null },
  8: { name: 'Nominal Top of the Atmosphere', units: null },
  9: { name: 'Sea Bottom', units: null },
  10: { name: 'Entire Atmosphere', units: null },
  11: { name: 'Cumulonimbus Base (CB)', units: 'm' },
  12: { name: 'Cumulonimbus Top (CT)', units: 'm' },
  13: {
    name: 'Lowest level where vertically integrated cloud cover exceeds the specified percentage (cloud base for a given percentage cloud cover)',
    units: '%',
  },
  14: { name: 'Level of free convection (LFC)', units: null },
  15: { name: 'Convection condensation level (CCL)', units: null },
  16: { name: 'Level of neutral buoyancy or equilibrium (LNB)', units: null },
  20: { name: 'Isothermal Level', units: 'K' },
  21: {
    name: 'Lowest level where mass density exceeds the specified value (base for a given threshold of mass density)',
    units: 'kg m-3',
  },
  22: {
    name: 'Highest level where mass density exceeds the specified value (top for a given threshold of mass density)',
    units: 'kg m-3',
  },
  23: {
    name: 'Lowest level where air concentration exceeds the specified value (base for a given threshold of air concentration',
    units: 'Bq m-3',
  },
  24: {
    name: 'Highest level where air concentration exceeds the specified value (top for a given threshold of air concentration)',
    units: 'Bq m-3',
  },
  25: {
    name: 'Highest level where radar reflectivity exceeds the specified value (echo top for a given threshold of reflectivity)',
    units: 'dBZ',
  },
  100: { name: 'Isobaric Surface', units: 'Pa' },
  101: { name: 'Mean Sea Level', units: null },
  102: { name: 'Specific Altitude Above Mean Sea Level', units: 'm' },
  103: { name: 'Specified Height Level Above Ground', units: 'm' },
  104: { name: 'Sigma Level', units: null },
  105: { name: 'Hybrid Level', units: null },
  106: { name: 'Depth Below Land Surface', units: 'm' },
  107: { name: 'Isentropic (theta) Level', units: 'K' },
  108: { name: 'Level at Specified Pressure Difference from Ground to Level', units: 'Pa' },
  109: { name: 'Potential Vorticity Surface', units: 'K m2 kg-1 s-1' },
  111: { name: 'Eta Level', units: null },
  113: { name: 'Logarithmic Hybrid Level', units: null },
  114: { name: 'Snow Level', units: 'Numeric' },
  115: { name: 'Sigma height level (see Note 4)', units: null },
  117: { name: 'Mixed Layer Depth', units: 'm' },
  118: { name: 'Hybrid Height Level', units: null },
  119: { name: 'Hybrid Pressure Level', units: null },
  150: { name: 'Generalized Vertical Height Coordinate (see Note 4)', units: null },
  151: { name: 'Soil level (See Note 5)', units: 'Numeric' },
  160: { name: 'Depth Below Sea Level', units: 'm' },
  161: { name: 'Depth Below Water Surface', units: 'm' },
  162: { name: 'Lake or River Bottom', units: null },
  163: { name: 'Bottom Of Sediment Layer', units: null },
  164: { name: 'Bottom Of Thermally Active Sediment Layer', units: null },
  165: { name: 'Bottom Of Sediment Layer Penetrated By Thermal Wave', units: null },
  166: { name: 'Mixing Layer', units: null },
  167: { name: 'Bottom of Root Zone', units: null },
  168: { name: 'Ocean Model Level', units: 'Numeric' },
  169: {
    name: 'Ocean level defined by water density (sigma-theta) difference from near-surface to level (see Note 7)',
    units: 'kg m-3',
  },
  170: {
    name: 'Ocean level defined by water potential temperature difference from near-surface to level (see Note 7)',
    units: 'K',
  },
  174: { name: 'Top Surface of Ice on Sea, Lake or River', units: null },
  175: { name: 'Top Surface of Ice, under Snow, on Sea, Lake or River', units: null },
  176: { name: 'Bottom Surface (underside) Ice on Sea, Lake or River', units: null },
  177: { name: 'Deep Soil (of indefinite depth)', units: null },
  179: { name: 'Top Surface of Glacier Ice and Inland Ice', units: null },
  180: { name: 'Deep Inland or Glacier Ice (of indefinite depth)', units: null },
  181: { name: 'Grid Tile Land Fraction as a Model Surface', units: null },
  182: { name: 'Grid Tile Water Fraction as a Model Surface', units: null },
  183: {
    name: 'Grid Tile Ice Fraction on Sea, Lake or River as a Model Surface',
    units: null,
  },
  184: {
    name: 'Grid Tile Glacier Ice and Inland Ice Fraction as a Model Surface',
    units: null,
  },
  200: { name: 'Entire atmosphere (considered as a single layer)', units: null },
  201: { name: 'Entire ocean (considered as a single layer)', units: null },
  204: { name: 'Highest tropospheric freezing level', units: null },
  206: { name: 'Grid scale cloud bottom level', units: null },
  207: { name: 'Grid scale cloud top level', units: null },
  209: { name: 'Boundary layer cloud bottom level', units: null },
  210: { name: 'Boundary layer cloud top level', units: null },
  211: { name: 'Boundary layer cloud layer', units: null },
  212: { name: 'Low cloud bottom level', units: null },
  213: { name: 'Low cloud top level', units: null },
  214: { name: 'Low cloud layer', units: null },
  215: { name: 'Cloud ceiling', units: null },
  216: { name: 'Effective Layer Top Level', units: 'm' },
  217: { name: 'Effective Layer Bottom Level', units: 'm' },
  218: { name: 'Effective Layer', units: 'm' },
  220: { name: 'Planetary Boundary Layer', units: null },
  221: { name: 'Layer Between Two Hybrid Levels', units: null },
  222: { name: 'Middle cloud bottom level', units: null },
  223: { name: 'Middle cloud top level', units: null },
  224: { name: 'Middle cloud layer', units: null },
  232: { name: 'High cloud bottom level', units: null },
  233: { name: 'High cloud top level', units: null },
  234: { name: 'High cloud layer', units: null },
  235: { name: 'Ocean Isotherm Level (1/10 ° C)', units: null },
  236: { name: 'Layer between two depths below ocean surface', units: null },
  237: { name: 'Bottom of Ocean Mixed Layer (m)', units: null },
  238: { name: 'Bottom of Ocean Isothermal Layer (m)', units: null },
  239: { name: 'Layer Ocean Surface        and 26C Ocean Isothermal Level', units: null },
  240: { name: 'Ocean Mixed Layer', units: null },
  241: { name: 'Ordered Sequence of Data', units: null },
  242: { name: 'Convective cloud bottom level', units: null },
  243: { name: 'Convective cloud top level', units: null },
  244: { name: 'Convective cloud layer', units: null },
  245: { name: 'Lowest level of the wet bulb zero', units: null },
  246: { name: 'Maximum equivalent potential temperature level', units: null },
  247: { name: 'Equilibrium level', units: null },
  248: { name: 'Shallow convective cloud bottom level', units: null },
  249: { name: 'Shallow convective cloud top level', units: null },
  251: { name: 'Deep convective cloud bottom level', units: null },
  252: { name: 'Deep convective cloud top level', units: null },
  253: { name: 'Lowest bottom level of supercooled liquid water layer', units: null },
  254: { name: 'Highest top level of supercooled liquid water layer', units: null },
  255: { name: 'Missing', units: null },
};

/**
 *  Table 4.7 - DERIVED FORECAST
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-7.shtml)
 * @param code
 */
export const lookupTable47: Record<number, string> = {
  0: 'Unweighted Mean of All Members',
  1: 'Weighted Mean of All Members',
  2: 'Standard Deviation with respect to Cluster Mean',
  3: 'Standard Deviation with respect to Cluster Mean, Normalized',
  4: 'Spread of All Members',
  5: 'Large Anomaly Index of All Members (see Note 1)',
  6: 'Unweighted Mean of the Cluster Members',
  7: 'Interquartile Range (Range between the 25th and 75th quantile)',
  8: 'Minimum Of All Ensemble Members (see Note 2)',
  9: 'Maximum Of All Ensemble Members (see Note 2)',
  192: 'Unweighted Mode of All Members',
  193: 'Percentile value (10%) of All Members',
  194: 'Percentile value (50%) of All Members',
  195: 'Percentile value (90%) of All Members',
  196: 'Statistically decided weights for each ensemble member',
  197: 'Climate Percentile (percentile values from climate distribution)',
  198: 'Deviation of Ensemble Mean from Daily Climatology',
  199: 'Extreme Forecast Index',
  200: 'Equally Weighted Mean',
  201: 'Percentile value (5%) of All Members',
  202: 'Percentile value (25%) of All Members',
  203: 'Percentile value (75%) of All Members',
  204: 'Percentile value (95%) of All Members',
  255: 'Missing',
};

/**
 *  Table 5.0 - CATEGORY BY PRODUCT DISCIPLINE
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table5-0.shtml)
 * @param code
 */
export const lookupTable50: Record<number, string> = {
  0: 'Grid Point Data - Simple Packing',
  1: 'Matrix Value at Grid Point - Simple Packing',
  2: 'Grid Point Data - Complex Packing',
  3: 'Grid Point Data - Complex Packing and Spatial Differencing',
  4: 'Grid Point Data - IEEE Floating Point Data',
  40: 'Grid Point Data - JPEG2000 Compression',
  41: 'Grid Point Data - PNG Compression',
  50: 'Spectral Data - Simple Packing',
  51: 'Spectral Data - Complex Packing',
  61: 'Grid Point Data - Simple Packing With Logarithm Pre-processing',
  200: 'Run Length Packing With Level Values',
  65535: 'Missing',
};

/**
 * Table 5.40 - TYPE OF COMPRESSION USED
 * [Read more](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table5-40.shtml)
 */
export const lookupTable540: Record<number, string> = {
  0: 'Lossless',
  1: 'Lossy',
  // Range 2-254 is Reserved
  255: 'Missing',
};

/**
 *  Table 5.1 - TYPE OF ORIGINAL FIELD VALUES
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table5-1.shtml)
 * @param code
 */
export const lookupTable51: Record<number, string> = {
  0: 'Floating Point',
  1: 'Integer',
  255: 'Missing',
};

/**
 *  Table A - Generating Process or Model from Originating Center 7
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/on388/tablec.html)
 * @param code
 */
export const lookupTableA: Record<number, string> = {
  0: 'Unknown',
  2: 'Ultra Violet Index Model',
  3: 'NCEP/ARL Transport and Dispersion Model',
  4: 'NCEP/ARL Smoke Model',
  5: 'Satellite Derived Precipitation and temperatures, from IR (See PDS Octet 41 ... for specific satellite ID)',
  6: 'NCEP/ARL Dust Model',
  10: 'Global Wind-Wave Forecast Model',
  11: 'Global Multi-Grid Wave Model (Static Grids)',
  12: 'Probabilistic Storm Surge (P-Surge)',
  13: 'Hurricane Multi-Grid Wave Model',
  14: 'Extra-tropical Storm Surge Atlantic Domain',
  15: 'Nearshore Wave Prediction System (NWPS)',
  16: 'Extra-Tropical Storm Surge (ETSS)',
  17: 'Extra-tropical Storm Surge Pacific Domain',
  18: 'Probabilistic Extra-Tropical Storm Surge (P-ETSS)',
  19: 'Limited-area Fine Mesh (LFM) analysis',
  20: 'Extra-tropical Storm Surge Micronesia Domain',
  25: 'Snow Cover Analysis',
  30: 'Forecaster generated field',
  31: 'Value added post processed field',
  42: 'Global Optimum Interpolation Analysis (GOI) from GFS model',
  43: 'Global Optimum Interpolation Analysis (GOI) from "Final" run',
  44: 'Sea Surface Temperature Analysis',
  45: 'Coastal Ocean Circulation Model',
  46: 'HYCOM - Global',
  47: 'HYCOM - North Pacific basin',
  48: 'HYCOM - North Atlantic basin',
  49: 'Ozone Analysis from TIROS Observations',
  52: 'Ozone Analysis from Nimbus 7 Observations',
  53: 'LFM-Fourth Order Forecast Model',
  64: 'Regional Optimum Interpolation Analysis (ROI)',
  68: '80 wave triangular, 18-layer Spectral model from GFS model',
  69: '80 wave triangular, 18 layer Spectral model from "Medium Range Forecast" run',
  70: 'Quasi-Lagrangian Hurricane Model (QLM)',
  71: 'Hurricane Weather Research and Forecasting (HWRF) Model',
  72: 'Hurricane Non-Hydrostatic Multiscale Model on the B Grid (HNMMB)',
  73: 'Fog Forecast model - Ocean Prod. Center',
  74: 'Gulf of Mexico Wind/Wave',
  75: 'Gulf of Alaska Wind/Wave',
  76: 'Bias corrected Medium Range Forecast',
  77: '126 wave triangular, 28 layer Spectral model from GFS model',
  78: '126 wave triangular, 28 layer Spectral model from "Medium Range Forecast" run',
  79: 'Backup from the previous run',
  80: '62 wave triangular, 28 layer Spectral model from "Medium Range Forecast" run',
  81: 'Analysis from GFS (Global Forecast System)',
  82: 'Analysis from GDAS (Global Data Assimilation System)',
  83: 'High Resolution Rapid Refresh (HRRR)',
  84: 'MESO NAM Model (currently 12 km)',
  85: 'Real Time Ocean Forecast System (RTOFS)',
  86: 'Early Hurricane Wind Speed Probability Model',
  87: 'CAC Ensemble Forecasts from Spectral (ENSMB)',
  88: 'NOAA Wave Watch III (NWW3) Ocean Wave Model',
  89: 'Non-hydrostatic Meso Model (NMM) (Currently 8 km)',
  90: '62 wave triangular, 28 layer spectral model extension of the "Medium Range Forecast" run',
  91: '62 wave triangular, 28 layer spectral model extension of the GFS model',
  92: '62 wave triangular, 28 layer spectral model run from the "Medium Range Forecast" final analysis',
  93: '62 wave triangular, 28 layer spectral model run from the T62 GDAS analysis of the "Medium Range Forecast" run',
  94: 'T170/L42 Global Spectral Model from MRF run',
  95: 'T126/L42 Global Spectral Model from MRF run',
  96: 'Global Forecast System Model T1534 - Forecast hours 00-384 T574 - Forecast hours 00-192 T190 - Forecast hours 204-384',
  98: 'Climate Forecast System Model -- Atmospheric model (GFS) coupled to a multi level ocean model. Currently GFS spectral model at T62, 64 levels coupled to 40 level MOM3 ocean model.',
  99: 'Miscellaneous Test ID',
  100: 'Miscellaneous Test ID',
  101: 'Conventional Observation Re-Analysis (CORE)',
  104: 'National Blend GRIB',
  105: 'Rapid Refresh (RAP)',
  107: 'Global Ensemble Forecast System (GEFS)',
  108: 'LAMP',
  109: 'RTMA (Real Time Mesoscale Analysis)',
  110: 'NAM Model - 15km version',
  111: 'NAM model, generic resolution (Used in SREF processing)',
  112: 'WRF-NMM model, generic resolution (Used in various runs) NMM=Nondydrostatic Mesoscale Model (NCEP)',
  113: 'Products from NCEP SREF processing',
  114: 'NAEFS Products from joined NCEP, CMC global ensembles',
  115: 'Downscaled GFS from NAM eXtension',
  116: 'WRF-EM model, generic resolution (Used in various runs) EM - Eulerian Mass-core (NCAR - aka Advanced Research WRF)',
  117: 'NEMS GFS Aerosol Component',
  118: 'URMA (UnRestricted Mesoscale Analysis)',
  119: 'WAM (Whole Atmosphere Model)',
  120: 'Ice Concentration Analysis',
  121: 'Western North Atlantic Regional Wave Model',
  122: 'Alaska Waters Regional Wave Model',
  123: 'North Atlantic Hurricane Wave Model',
  124: 'Eastern North Pacific Regional Wave Model',
  125: 'North Pacific Hurricane Wave Model',
  126: 'Sea Ice Forecast Model',
  127: 'Lake Ice Forecast Model',
  128: 'Global Ocean Forecast Model',
  129: 'Global Ocean Data Analysis System (GODAS)',
  130: 'Merge of fields from the RUC, NAM, and Spectral Model',
  131: 'Great Lakes Wave Model',
  132: 'High Resolution Ensemble Forecast (HREF)',
  133: 'Great Lakes Short Range Wave Model',
  134: 'Rapid Refresh Forecast System (RRFS)',
  135: 'Hurricane Analysis and Forecast System (HAFS)',
  140: 'North American Regional Reanalysis (NARR)',
  141: 'Land Data Assimilation and Forecast System',
  150: 'NWS River Forecast System (NWSRFS)',
  151: 'NWS Flash Flood Guidance System (NWSFFGS)',
  152: 'WSR-88D Stage II Precipitation Analysis',
  153: 'WSR-88D Stage III Precipitation Analysis',
  180: 'Quantitative Precipitation Forecast generated by NCEP',
  181: 'River Forecast Center Quantitative Precipitation Forecast mosaic generated by NCEP',
  182: 'River Forecast Center Quantitative Precipitation estimate mosaic generated by NCEP',
  183: 'NDFD product generated by NCEP/HPC',
  184: 'Climatological Calibrated Precipitation Analysis - CCPA',
  190: 'National Convective Weather Diagnostic generated by NCEP/AWC',
  191: 'Current Icing Potential automated product genterated by NCEP/AWC',
  192: 'Analysis product from NCEP/AWC',
  193: 'Forecast product from NCEP/AWC',
  195: 'Climate Data Assimilation System 2 (CDAS2)',
  196: 'Climate Data Assimilation System 2 (CDAS2) - used for regeneration runs',
  197: 'Climate Data Assimilation System (CDAS)',
  198: 'Climate Data Assimilation System (CDAS) - used for regeneration runs',
  199: 'Climate Forecast System Reanalysis (CFSR) -- Atmospheric model (GFS) coupled to a multi level ocean, land and seaice model.   Currently GFS spectral model at T382, 64 levels coupled to 40 level MOM4 ocean model.',
  200: 'CPC Manual Forecast Product',
  201: 'CPC Automated Product',
  210: 'EPA Air Quality Forecast - Currently North East US domain',
  211: 'EPA Air Quality Forecast - Currently Eastern US domain',
  215: 'SPC Manual Forecast Product',
  220: 'NCEP/OPC automated product',
  255: 'Missing',
};

/**
 *  Table C - National Sub-Centerss
 *
 * [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/on388/tablec.html)
 * @param code
 */
export const lookupTableC: Record<number, string> = {
  0: 'null',
  1: 'NCEP Re-Analysis Project',
  2: 'NCEP Ensemble Products',
  3: 'NCEP Central Operations',
  4: 'Environmental Modeling Center',
  5: 'Weather Prediction Center',
  6: 'Ocean Prediction Center',
  7: 'Climate Prediction Center',
  8: 'Aviation Weather Center',
  9: 'Storm Prediction Center',
  10: 'National Hurricane Center',
  11: 'NWS Techniques Development Laboratory',
  12: 'NESDIS Office of Research and Applications',
  13: 'Federal Aviation Administration',
  14: 'NWS Meteorological Development Laboratory',
  15: 'North American Regional Reanalysis Project',
  16: 'Space Weather Prediction Center',
  17: 'ESRL Global Systems Division',
};
