[package]
name = "parsers"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
# LOCAL dependencies
s2json = { workspace = true }
# Open S2 dependencies
pbf = { workspace = true }
# External dependencies
libm = { workspace = true }
half = { workspace = true }
serde = { workspace = true }
regex = { workspace = true }
# STD dependencies
memmap2 = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["std"]
std = ["memmap2"]
