[workspace]
members = [
  "rust/data_store",
  "rust/data_structures",
  "rust/geometry",
  "rust/lib",
  "rust/parsers",
  "rust/proj",
  "rust/readers",
  "rust/space",
  "rust/tools",
  "rust/util",
  "rust/writers"
]
default-members = ["rust/lib"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2024"
authors = ["Craig O'Connor <oconnorct1@gmail.com>"]
description = "A collection of geospatial tools primarily designed for WGS84, Web Mercator, and S2."
documentation = "https://docs.rs/gis-tools"
homepage = "https://github.com/OpenS2/gis-tools"
repository = "https://github.com/OpenS2/gis-tools"
readme = "README.md"
categories = ["no-std", "algorithms"]
keywords = ["tools", "s2", "gis", "low-cost-code"]
license = "SEE LICENSE"

[workspace.dependencies]
# Open S2 dependencies
earclip = "1.5"
open-vector-tile = "1.8"
pbf = "1.21"
s2json = "1.34"
s2-tilejson = "1.8"
# External shared dependencies
libm = "0.2"
half = "2.6"
regex = { version = "1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
# Optional std dependencies
memmap2 = { version = "0.9" }
flate2 = { version = "1" }
brotli = { version = "8" }
ruzstd = { version = "0.8" }
image = { version = "0.25" }
# TMP dependencies (workspace dev doesn't work)
tempfile = "3"
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.9"
