[package]
name = "gis-tools"
version = "1.1.0"
rust-version = "1.86.0"
edition = "2024"
authors = ["Craig O'Connor <oconnorct1@gmail.com>"]
description = "A collection of geospatial tools primarily designed for WGS84, Web Mercator, and S2."
documentation = "https://docs.rs/gis-tools"
homepage = "https://github.com/Open-S2/gis-tools"
repository = "https://github.com/Open-S2/gis-tools"
readme = "README.md"
categories = ["no-std", "algorithms"]
keywords = ["tools", "s2", "gis", "low-cost-code"]
license = "SEE LICENSE"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[lib]
name = "gistools"
path = "rust/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Open S2 dependencies
earclip = "1.6"
open-vector-tile = "1.9"
pbf = "1.22"
s2json = "1.35"
s2-tilejson = "1.9"
# External shared dependencies
libm = "0.2"
half = "2.6"
regex = { version = "1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
# Optional std dependencies
# rayon = { version = "1", optional = true }
memmap2 = { version = "0.9", optional = true }
flate2 = { version = "1", optional = true }
brotli = { version = "8", optional = true }
ruzstd = { version = "0.8", optional = true }
image = { version = "0.25", optional = true }

[dev-dependencies]
tempfile = "3"
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.9"

[features]
default = ["std", "quadratic"] # Default feature
quadratic = []                 # Feature for quadratic projection
tan = []                       # Feature for tangential projection
linear = []                    # Feature for linear projection
# Conditional std feature enabling quadratic or other projection features
std = ["memmap2", "flate2", "brotli", "ruzstd", "image"]

[[bench]]
name = "s2_cells"
harness = false

[[bench]]
name = "delaunator"
harness = false

[profile.bench]
inherits = "release"
opt-level = 3

[profile.dev.package]
image.opt-level = 3
