[package]
name = "data_structures"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
# LOCAL dependencies
parsers = { path = "../parsers" }
data_store = { path = "../data_store" }
geometry = { path = "../geometry" }
util = { path = "../util" }
# OpenS2 dependencies
s2json = { workspace = true }
# External dependencies
libm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
readers = { path = "../readers" }
gis-tools = { path = "../lib" }
