[package]
name = "readers"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
# LOCAL dependencies
parsers = { path = "../parsers" }
geometry = { path = "../geometry" }
data_store = { path = "../data_store" }
data_structures = { path = "../data_structures" }
proj = { path = "../proj" }
util = { path = "../util" }
# OpenS2 dependencies
pbf = { workspace = true }
s2json = { workspace = true }
s2-tilejson = { workspace = true }
# External dependencies
serde = { workspace = true }
serde_json = { workspace = true }
libm = { workspace = true }
# STD dependencies
memmap2 = { workspace = true, optional = true }
image = { workspace = true, optional = true }

[features]
default = ["std"]
# Conditional std feature enabling quadratic or other projection features
std = ["memmap2", "image"]
