/// # ON388 - TABLE A - GENERATING PROCESS OR MODEL
///
/// **Details**:
/// - **Originating Center**: 7 (US-NWS, NCEP)
/// - **GRIB2 - Product Definition Template in Octet**: 14
/// - **Revised**: 05/26/2023
///
/// **Reserved Ranges**:
/// - `0-1`: Reserved
/// - `7-9`: Reserved
/// - `19`: Reserved
/// - `24`: Reserved
/// - `26-29`: Reserved
/// - `32-41`: Reserved
/// - `50-51`: Reserved
/// - `53-63`: Reserved
/// - `65-67`: Reserved
/// - `79`: Reserved
/// - `102-103`: Reserved
/// - `106`: Reserved
/// - `142-149`: Reserved
/// - `194`: Reserved
/// - `202-209`: Reserved
/// - `212-214`: Reserved
/// - `216-219`: Reserved
/// - `221-230`: Reserved for WPC products
/// - `231-254`: Reserved
///
/// **Special Value**:
/// - `255`: Missing
///
/// ## Description
/// This table defines the data template definitions used by Originating Center 7 (US-NWS, NCEP) in GRIB2 files,
/// specifying various generating processes or models and their corresponding template references.
///
/// ## Notes
/// - Red text depicts changes made since 01/25/2022
#[repr(u8)]
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Grib2TableA {
    UltraVioletIndexModel = 2,
    NcepArlTransportAndDispersionModel = 3,
    NcepArlSmokeModel = 4,
    SatelliteDerivedPrecipitationAndTemperaturesFromIr = 5,
    NcepArlDustModel = 6,
    GlobalWindWaveForecastModel = 10,
    GlobalMultiGridWaveModelStaticGrids = 11,
    ProbabilisticStormSurgePSurge = 12,
    HurricaneMultiGridWaveModel = 13,
    ExtraTropicalStormSurgeAtlanticDomain = 14,
    NearshoreWavePredictionSystemNwps = 15,
    ExtraTropicalStormSurgeEtss = 16,
    ExtraTropicalStormSurgePacificDomain = 17,
    ProbabilisticExtraTropicalStormSurgePEtss = 18,
    ExtraTropicalStormSurgeMicronesiaDomain = 20,
    ExtraTropicalStormSurgeAtlanticDomain3d = 21,
    ExtraTropicalStormSurgePacificDomain3d = 22,
    ExtraTropicalStormSurgeMicronesiaDomain3d = 23,
    SnowCoverAnalysis = 25,
    ForecasterGeneratedField = 30,
    ValueAddedPostProcessedField = 31,
    GlobalOptimumInterpolationAnalysisGoiFromGfsModel = 42,
    GlobalOptimumInterpolationAnalysisGoiFromFinalRun = 43,
    SeaSurfaceTemperatureAnalysis = 44,
    CoastalOceanCirculationModel = 45,
    HycomGlobal = 46,
    HycomNorthPacificBasin = 47,
    HycomNorthAtlanticBasin = 48,
    OzoneAnalysisFromTirosObservations = 49,
    OzoneAnalysisFromNimbus7Observations = 52,
    RegionalOptimumInterpolationAnalysisRoi = 64,
    _180WaveTriangular18LayerSpectralModelFromGfsModel = 68,
    WaveTriangular18LayerSpectralModelFromMediumRangeForecastRun = 69,
    QuasiLagrangianHurricaneModelQlm = 70,
    HurricaneWeatherResearchAndForecastingHwrf = 71,
    HurricaneNonHydrostaticMultiscaleModelOnTheBGridHnmmb = 72,
    FogForecastModelOceanProdCenter = 73,
    GulfOfMexicoWindWave = 74,
    GulfOfAlaskaWindWave = 75,
    BiasCorrectedMediumRangeForecast = 76,
    _126WaveTriangular28LayerSpectralModelFromGfsModel = 77,
    _126WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun = 78,
    WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun = 80,
    AnalysisFromGfsGlobalForecastSystem = 81,
    AnalysisFromGdasGlobalDataAssimilationSystem = 82,
    HighResolutionRapidRefreshHrrr = 83,
    MesoNamModelCurrently12Km = 84,
    RealTimeOceanForecastSystemRtofs = 85,
    EarlyHurricaneWindSpeedProbabilityModel = 86,
    CacEnsembleForecastsFromSpectralEnsmb = 87,
    NoaaWaveWatchIiiNww3OceanWaveModel = 88,
    NonHydrostaticMesoModelNmmCurrently8Km = 89,
    WaveTriangular28LayerSpectralModelExtensionOfMediumRangeForecastRun = 90,
    WaveTriangular28LayerSpectralModelExtensionOfGfsModel = 91,
    WaveTriangular28LayerSpectralModelRunFromMediumRangeForecastFinalAnalysis = 92,
    WaveTriangular28LayerSpectralModelRunFromT62GdasAnalysisOfMediumRangeForecastRun = 93,
    T170L42GlobalSpectralModelFromMrfRun = 94,
    T126L42GlobalSpectralModelFromMrfRun = 95,
    GlobalForecastSystemModel = 96,
    ClimateForecastSystemModel = 98,
    MiscellaneousTestId99 = 99,
    MiscellaneousTestId100 = 100,
    ConventionalObservationReAnalysisCore = 101,
    NationalBlendGrib = 104,
    RapidRefreshRap = 105,
    GlobalEnsembleForecastSystemGefs = 107,
    LocalizedAviationMosProgramLamp = 108,
    RealTimeMesoscaleAnalysisRtma = 109,
    NamModel15KmVersion = 110,
    NamModelGenericResolution = 111,
    WrfNmmModelGenericResolution = 112,
    ProductsFromNcepSrefProcessing = 113,
    NaefsProductsFromJoinedNcepCmcGlobalEnsembles = 114,
    DownscaledGfsFromNamExtension = 115,
    WrfEmModelGenericResolution = 116,
    NemsGfsAerosolComponent = 117,
    UnrestrictedMesoscaleAnalysisUrma = 118,
    WamWholeAtmosphereModel = 119,
    IceConcentrationAnalysis = 120,
    WesternNorthAtlanticRegionalWaveModel = 121,
    AlaskaWatersRegionalWaveModel = 122,
    NorthAtlanticHurricaneWaveModel = 123,
    EasternNorthPacificRegionalWaveModel = 124,
    NorthPacificHurricaneWaveModel = 125,
    SeaIceForecastModel = 126,
    LakeIceForecastModel = 127,
    GlobalOceanForecastModel = 128,
    GlobalOceanDataAnalysisSystemGodas = 129,
    MergeOfFieldsFromTheRucNamAndSpectralModel = 130,
    GreatLakesWaveModel = 131,
    HighResolutionEnsembleForecastHref = 132,
    GreatLakesShortRangeWaveModel = 133,
    RapidRefreshForecastSystemRrfs = 134,
    HurricaneAnalysisAndForecastSystemHafs = 135,
    NorthAmericanRegionalReanalysisNarr = 140,
    LandDataAssimilationAndForecastSystem = 141,
    NwsRiverForecastSystemNwsrfs = 150,
    NwsFlashFloodGuidanceSystemNwsffgs = 151,
    Wsr88dStageIiPrecipitationAnalysis = 152,
    Wsr88dStageIiiPrecipitationAnalysis = 153,
    QuantitativePrecipitationForecastGeneratedByNcep = 180,
    RiverForecastCenterQuantitativePrecipitationForecastMosaicGeneratedByNcep = 181,
    RiverForecastCenterQuantitativePrecipitationEstimateMosaicGeneratedByNcep = 182,
    NdfdProductGeneratedByNcepHpc = 183,
    ClimatologicalCalibratedPrecipitationAnalysisCcpa = 184,
    NationalConvectiveWeatherDiagnosticGeneratedByNcepAwc = 190,
    CurrentIcingPotentialAutomatedProductGeneratedByNcepAwc = 191,
    AnalysisProductFromNcepAwc = 192,
    ForecastProductFromNcepAwc = 193,
    ClimateDataAssimilationSystem2Cdas2 = 195,
    ClimateDataAssimilationSystem2Cdas2UsedForRegenerationRuns = 196,
    ClimateDataAssimilationSystemCdas = 197,
    ClimateDataAssimilationSystemCdasUsedForRegenerationRuns = 198,
    ClimateForecastSystemReanalysisCfsr = 199,
    CpcManualForecastProduct = 200,
    CpcAutomatedProduct = 201,
    EpaAirQualityForecastNorthEastUsDomain = 210,
    EpaAirQualityForecastEasternUsDomain = 211,
    SpcManualForecastProduct = 215,
    NcepOpcAutomatedProduct = 220,
    Missing = 255,
}
impl From<u8> for Grib2TableA {
    fn from(val: u8) -> Self {
        match val {
            2 => Self::UltraVioletIndexModel,
            3 => Self::NcepArlTransportAndDispersionModel,
            4 => Self::NcepArlSmokeModel,
            5 => Self::SatelliteDerivedPrecipitationAndTemperaturesFromIr,
            6 => Self::NcepArlDustModel,
            10 => Self::GlobalWindWaveForecastModel,
            11 => Self::GlobalMultiGridWaveModelStaticGrids,
            12 => Self::ProbabilisticStormSurgePSurge,
            13 => Self::HurricaneMultiGridWaveModel,
            14 => Self::ExtraTropicalStormSurgeAtlanticDomain,
            15 => Self::NearshoreWavePredictionSystemNwps,
            16 => Self::ExtraTropicalStormSurgeEtss,
            17 => Self::ExtraTropicalStormSurgePacificDomain,
            18 => Self::ProbabilisticExtraTropicalStormSurgePEtss,
            20 => Self::ExtraTropicalStormSurgeMicronesiaDomain,
            21 => Self::ExtraTropicalStormSurgeAtlanticDomain3d,
            22 => Self::ExtraTropicalStormSurgePacificDomain3d,
            23 => Self::ExtraTropicalStormSurgeMicronesiaDomain3d,
            25 => Self::SnowCoverAnalysis,
            30 => Self::ForecasterGeneratedField,
            31 => Self::ValueAddedPostProcessedField,
            42 => Self::GlobalOptimumInterpolationAnalysisGoiFromGfsModel,
            43 => Self::GlobalOptimumInterpolationAnalysisGoiFromFinalRun,
            44 => Self::SeaSurfaceTemperatureAnalysis,
            45 => Self::CoastalOceanCirculationModel,
            46 => Self::HycomGlobal,
            47 => Self::HycomNorthPacificBasin,
            48 => Self::HycomNorthAtlanticBasin,
            49 => Self::OzoneAnalysisFromTirosObservations,
            52 => Self::OzoneAnalysisFromNimbus7Observations,
            64 => Self::RegionalOptimumInterpolationAnalysisRoi,
            68 => Self::_180WaveTriangular18LayerSpectralModelFromGfsModel,
            69 => Self::WaveTriangular18LayerSpectralModelFromMediumRangeForecastRun,
            70 => Self::QuasiLagrangianHurricaneModelQlm,
            71 => Self::HurricaneWeatherResearchAndForecastingHwrf,
            72 => Self::HurricaneNonHydrostaticMultiscaleModelOnTheBGridHnmmb,
            73 => Self::FogForecastModelOceanProdCenter,
            74 => Self::GulfOfMexicoWindWave,
            75 => Self::GulfOfAlaskaWindWave,
            76 => Self::BiasCorrectedMediumRangeForecast,
            77 => Self::_126WaveTriangular28LayerSpectralModelFromGfsModel,
            78 => Self::_126WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun,
            80 => Self::WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun,
            81 => Self::AnalysisFromGfsGlobalForecastSystem,
            82 => Self::AnalysisFromGdasGlobalDataAssimilationSystem,
            83 => Self::HighResolutionRapidRefreshHrrr,
            84 => Self::MesoNamModelCurrently12Km,
            85 => Self::RealTimeOceanForecastSystemRtofs,
            86 => Self::EarlyHurricaneWindSpeedProbabilityModel,
            87 => Self::CacEnsembleForecastsFromSpectralEnsmb,
            88 => Self::NoaaWaveWatchIiiNww3OceanWaveModel,
            89 => Self::NonHydrostaticMesoModelNmmCurrently8Km,
            90 => Self::WaveTriangular28LayerSpectralModelExtensionOfMediumRangeForecastRun,
            91 => Self::WaveTriangular28LayerSpectralModelExtensionOfGfsModel,
            92 => Self::WaveTriangular28LayerSpectralModelRunFromMediumRangeForecastFinalAnalysis,
            93 => Self::WaveTriangular28LayerSpectralModelRunFromT62GdasAnalysisOfMediumRangeForecastRun,
            94 => Self::T170L42GlobalSpectralModelFromMrfRun,
            95 => Self::T126L42GlobalSpectralModelFromMrfRun,
            96 => Self::GlobalForecastSystemModel,
            98 => Self::ClimateForecastSystemModel,
            99 => Self::MiscellaneousTestId99,
            100 => Self::MiscellaneousTestId100,
            101 => Self::ConventionalObservationReAnalysisCore,
            104 => Self::NationalBlendGrib,
            105 => Self::RapidRefreshRap,
            107 => Self::GlobalEnsembleForecastSystemGefs,
            108 => Self::LocalizedAviationMosProgramLamp,
            109 => Self::RealTimeMesoscaleAnalysisRtma,
            110 => Self::NamModel15KmVersion,
            111 => Self::NamModelGenericResolution,
            112 => Self::WrfNmmModelGenericResolution,
            113 => Self::ProductsFromNcepSrefProcessing,
            114 => Self::NaefsProductsFromJoinedNcepCmcGlobalEnsembles,
            115 => Self::DownscaledGfsFromNamExtension,
            116 => Self::WrfEmModelGenericResolution,
            117 => Self::NemsGfsAerosolComponent,
            118 => Self::UnrestrictedMesoscaleAnalysisUrma,
            119 => Self::WamWholeAtmosphereModel,
            120 => Self::IceConcentrationAnalysis,
            121 => Self::WesternNorthAtlanticRegionalWaveModel,
            122 => Self::AlaskaWatersRegionalWaveModel,
            123 => Self::NorthAtlanticHurricaneWaveModel,
            124 => Self::EasternNorthPacificRegionalWaveModel,
            125 => Self::NorthPacificHurricaneWaveModel,
            126 => Self::SeaIceForecastModel,
            127 => Self::LakeIceForecastModel,
            128 => Self::GlobalOceanForecastModel,
            129 => Self::GlobalOceanDataAnalysisSystemGodas,
            130 => Self::MergeOfFieldsFromTheRucNamAndSpectralModel,
            131 => Self::GreatLakesWaveModel,
            132 => Self::HighResolutionEnsembleForecastHref,
            133 => Self::GreatLakesShortRangeWaveModel,
            134 => Self::RapidRefreshForecastSystemRrfs,
            135 => Self::HurricaneAnalysisAndForecastSystemHafs,
            140 => Self::NorthAmericanRegionalReanalysisNarr,
            141 => Self::LandDataAssimilationAndForecastSystem,
            150 => Self::NwsRiverForecastSystemNwsrfs,
            151 => Self::NwsFlashFloodGuidanceSystemNwsffgs,
            152 => Self::Wsr88dStageIiPrecipitationAnalysis,
            153 => Self::Wsr88dStageIiiPrecipitationAnalysis,
            180 => Self::QuantitativePrecipitationForecastGeneratedByNcep,
            181 => Self::RiverForecastCenterQuantitativePrecipitationForecastMosaicGeneratedByNcep,
            182 => Self::RiverForecastCenterQuantitativePrecipitationEstimateMosaicGeneratedByNcep,
            183 => Self::NdfdProductGeneratedByNcepHpc,
            184 => Self::ClimatologicalCalibratedPrecipitationAnalysisCcpa,
            190 => Self::NationalConvectiveWeatherDiagnosticGeneratedByNcepAwc,
            191 => Self::CurrentIcingPotentialAutomatedProductGeneratedByNcepAwc,
            192 => Self::AnalysisProductFromNcepAwc,
            193 => Self::ForecastProductFromNcepAwc,
            195 => Self::ClimateDataAssimilationSystem2Cdas2,
            196 => Self::ClimateDataAssimilationSystem2Cdas2UsedForRegenerationRuns,
            197 => Self::ClimateDataAssimilationSystemCdas,
            198 => Self::ClimateDataAssimilationSystemCdasUsedForRegenerationRuns,
            199 => Self::ClimateForecastSystemReanalysisCfsr,
            200 => Self::CpcManualForecastProduct,
            201 => Self::CpcAutomatedProduct,
            210 => Self::EpaAirQualityForecastNorthEastUsDomain,
            211 => Self::EpaAirQualityForecastEasternUsDomain,
            215 => Self::SpcManualForecastProduct,
            220 => Self::NcepOpcAutomatedProduct,
            _ => Self::Missing,
        }
    }
}
impl core::fmt::Display for Grib2TableA {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let desc = match self {
            Self::UltraVioletIndexModel => "Ultra Violet Index Model",
            Self::NcepArlTransportAndDispersionModel => "NCEP/ARL Transport and Dispersion Model",
            Self::NcepArlSmokeModel => "NCEP/ARL Smoke Model",
            Self::SatelliteDerivedPrecipitationAndTemperaturesFromIr => "Satellite Derived Precipitation and temperatures, from IR (See PDS Octet 41 ... for specific satellite ID)",
            Self::NcepArlDustModel => "NCEP/ARL Dust Model",
            Self::GlobalWindWaveForecastModel => "Global Wind-Wave Forecast Model",
            Self::GlobalMultiGridWaveModelStaticGrids => "Global Multi-Grid Wave Model (Static Grids)",
            Self::ProbabilisticStormSurgePSurge => "Probabilistic Storm Surge (P-Surge)",
            Self::HurricaneMultiGridWaveModel => "Hurricane Multi-Grid Wave Model",
            Self::ExtraTropicalStormSurgeAtlanticDomain => "Extra-tropical Storm Surge Atlantic Domain",
            Self::NearshoreWavePredictionSystemNwps => "Nearshore Wave Prediction System (NWPS)",
            Self::ExtraTropicalStormSurgeEtss => "Extra-Tropical Storm Surge (ETSS)",
            Self::ExtraTropicalStormSurgePacificDomain => "Extra-tropical Storm Surge Pacific Domain",
            Self::ProbabilisticExtraTropicalStormSurgePEtss => "Probabilistic Extra-Tropical Storm Surge (P-ETSS)",
            Self::ExtraTropicalStormSurgeMicronesiaDomain => "Extra-tropical Storm Surge Micronesia Domain",
            Self::ExtraTropicalStormSurgeAtlanticDomain3d => "Extra-tropical Storm Surge Atlantic Domain (3D)",
            Self::ExtraTropicalStormSurgePacificDomain3d => "Extra-tropical Storm Surge Pacific Domain (3D)",
            Self::ExtraTropicalStormSurgeMicronesiaDomain3d => "Extra-tropical Storm Surge Micronesia Domain (3D)",
            Self::SnowCoverAnalysis => "Snow Cover Analysis",
            Self::ForecasterGeneratedField => "Forecaster generated field",
            Self::ValueAddedPostProcessedField => "Value added post processed field",
            Self::GlobalOptimumInterpolationAnalysisGoiFromGfsModel => "Global Optimum Interpolation Analysis (GOI) from GFS model",
            Self::GlobalOptimumInterpolationAnalysisGoiFromFinalRun => "Global Optimum Interpolation Analysis (GOI) from \"Final\" run",
            Self::SeaSurfaceTemperatureAnalysis => "Sea Surface Temperature Analysis",
            Self::CoastalOceanCirculationModel => "Coastal Ocean Circulation Model",
            Self::HycomGlobal => "HYCOM - Global",
            Self::HycomNorthPacificBasin => "HYCOM - North Pacific basin",
            Self::HycomNorthAtlanticBasin => "HYCOM - North Atlantic basin",
            Self::OzoneAnalysisFromTirosObservations => "Ozone Analysis from TIROS Observations",
            Self::OzoneAnalysisFromNimbus7Observations => "Ozone Analysis from Nimbus 7 Observations",
            Self::RegionalOptimumInterpolationAnalysisRoi => "Regional Optimum Interpolation Analysis (ROI)",
            Self::_180WaveTriangular18LayerSpectralModelFromGfsModel => "80 wave triangular, 18-layer Spectral model from GFS model",
            Self::WaveTriangular18LayerSpectralModelFromMediumRangeForecastRun => "80 wave triangular, 18 layer Spectral model from \"Medium Range Forecast\" run",
            Self::QuasiLagrangianHurricaneModelQlm => "Quasi-Lagrangian Hurricane Model (QLM)",
            Self::HurricaneWeatherResearchAndForecastingHwrf => "Hurricane Weather Research and Forecasting (HWRF)",
            Self::HurricaneNonHydrostaticMultiscaleModelOnTheBGridHnmmb => "Hurricane Non-Hydrostatic Multiscale Model on the B Grid (HNMMB)",
            Self::FogForecastModelOceanProdCenter => "Fog Forecast model - Ocean Prod. Center",
            Self::GulfOfMexicoWindWave => "Gulf of Mexico Wind/Wave",
            Self::GulfOfAlaskaWindWave => "Gulf of Alaska Wind/Wave",
            Self::BiasCorrectedMediumRangeForecast => "Bias corrected Medium Range Forecast",
            Self::_126WaveTriangular28LayerSpectralModelFromGfsModel => "126 wave triangular, 28 layer Spectral model from GFS model",
            Self::_126WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun => "126 wave triangular, 28 layer Spectral model from \"Medium Range Forecast\" run",
            Self::WaveTriangular28LayerSpectralModelFromMediumRangeForecastRun => "62 wave triangular, 28 layer Spectral model from \"Medium Range Forecast\" run",
            Self::AnalysisFromGfsGlobalForecastSystem => "Analysis from GFS (Global Forecast System)",
            Self::AnalysisFromGdasGlobalDataAssimilationSystem => "Analysis from GDAS (Global Data Assimilation System)",
            Self::HighResolutionRapidRefreshHrrr => "High Resolution Rapid Refresh (HRRR)",
            Self::MesoNamModelCurrently12Km => "MESO NAM Model (currently 12 km)",
            Self::RealTimeOceanForecastSystemRtofs => "Real Time Ocean Forecast System (RTOFS)",
            Self::EarlyHurricaneWindSpeedProbabilityModel => "Early Hurricane Wind Speed Probability Model",
            Self::CacEnsembleForecastsFromSpectralEnsmb => "CAC Ensemble Forecasts from Spectral (ENSMB)",
            Self::NoaaWaveWatchIiiNww3OceanWaveModel => "NOAA Wave Watch III (NWW3) Ocean Wave Model",
            Self::NonHydrostaticMesoModelNmmCurrently8Km => "Non-hydrostatic Meso Model (NMM) (Currently 8 km)",
            Self::WaveTriangular28LayerSpectralModelExtensionOfMediumRangeForecastRun => "62 wave triangular, 28 layer spectral model extension of the \"Medium Range Forecast\" run",
            Self::WaveTriangular28LayerSpectralModelExtensionOfGfsModel => "62 wave triangular, 28 layer spectral model extension of the GFS model",
            Self::WaveTriangular28LayerSpectralModelRunFromMediumRangeForecastFinalAnalysis => "62 wave triangular, 28 layer spectral model run from the \"Medium Range Forecast\" final analysis",
            Self::WaveTriangular28LayerSpectralModelRunFromT62GdasAnalysisOfMediumRangeForecastRun => "62 wave triangular, 28 layer spectral model run from the T62 GDAS analysis of the \"Medium Range Forecast\" run",
            Self::T170L42GlobalSpectralModelFromMrfRun => "T170/L42 Global Spectral Model from MRF run",
            Self::T126L42GlobalSpectralModelFromMrfRun => "T126/L42 Global Spectral Model from MRF run",
            Self::GlobalForecastSystemModel => "Global Forecast System Model. T1534 - Forecast hours 00-384; T574 - Forecast hours 00-192; T190 - Forecast hours 204-384",
            Self::ClimateForecastSystemModel => "Climate Forecast System Model -- Atmospheric model (GFS) coupled to a multi level ocean model. Currently GFS spectral model at T62, 64 levels coupled to 40 level MOM3 ocean model.",
            Self::MiscellaneousTestId99 => "Miscellaneous Test ID",
            Self::MiscellaneousTestId100 => "Miscellaneous Test ID",
            Self::ConventionalObservationReAnalysisCore => "Conventional Observation Re-Analysis (CORE)",
            Self::NationalBlendGrib => "National Blend GRIB",
            Self::RapidRefreshRap => "Rapid Refresh (RAP)",
            Self::GlobalEnsembleForecastSystemGefs => "Global Ensemble Forecast System (GEFS)",
            Self::LocalizedAviationMosProgramLamp => "Localized Aviation MOS Program (LAMP)",
            Self::RealTimeMesoscaleAnalysisRtma => "Real Time Mesoscale Analysis (RTMA)",
            Self::NamModel15KmVersion => "NAM Model - 15km version",
            Self::NamModelGenericResolution => "NAM model, generic resolution (Used in SREF processing)",
            Self::WrfNmmModelGenericResolution => "WRF-NMM model, generic resolution (Used in various runs) NMM=Nondydrostatic Mesoscale Model (NCEP)",
            Self::ProductsFromNcepSrefProcessing => "Products from NCEP SREF processing",
            Self::NaefsProductsFromJoinedNcepCmcGlobalEnsembles => "NAEFS Products from joined NCEP, CMC global ensembles",
            Self::DownscaledGfsFromNamExtension => "Downscaled GFS from NAM eXtension",
            Self::WrfEmModelGenericResolution => "WRF-EM model, generic resolution (Used in various runs) EM - Eulerian Mass-core (NCAR - aka Advanced Research WRF)",
            Self::NemsGfsAerosolComponent => "NEMS GFS Aerosol Component",
            Self::UnrestrictedMesoscaleAnalysisUrma => "UnRestricted Mesoscale Analysis (URMA)",
            Self::WamWholeAtmosphereModel => "WAM (Whole Atmosphere Model)",
            Self::IceConcentrationAnalysis => "Ice Concentration Analysis",
            Self::WesternNorthAtlanticRegionalWaveModel => "Western North Atlantic Regional Wave Model",
            Self::AlaskaWatersRegionalWaveModel => "Alaska Waters Regional Wave Model",
            Self::NorthAtlanticHurricaneWaveModel => "North Atlantic Hurricane Wave Model",
            Self::EasternNorthPacificRegionalWaveModel => "Eastern North Pacific Regional Wave Model",
            Self::NorthPacificHurricaneWaveModel => "North Pacific Hurricane Wave Model",
            Self::SeaIceForecastModel => "Sea Ice Forecast Model",
            Self::LakeIceForecastModel => "Lake Ice Forecast Model",
            Self::GlobalOceanForecastModel => "Global Ocean Forecast Model",
            Self::GlobalOceanDataAnalysisSystemGodas => "Global Ocean Data Analysis System (GODAS)",
            Self::MergeOfFieldsFromTheRucNamAndSpectralModel => "Merge of fields from the RUC, NAM, and Spectral Model",
            Self::GreatLakesWaveModel => "Great Lakes Wave Model",
            Self::HighResolutionEnsembleForecastHref => "High Resolution Ensemble Forecast (HREF)",
            Self::GreatLakesShortRangeWaveModel => "Great Lakes Short Range Wave Model",
            Self::RapidRefreshForecastSystemRrfs => "Rapid Refresh Forecast System (RRFS)",
            Self::HurricaneAnalysisAndForecastSystemHafs => "Hurricane Analysis and Forecast System (HAFS)",
            Self::NorthAmericanRegionalReanalysisNarr => "North American Regional Reanalysis (NARR)",
            Self::LandDataAssimilationAndForecastSystem => "Land Data Assimilation and Forecast System",
            Self::NwsRiverForecastSystemNwsrfs => "NWS River Forecast System (NWSRFS)",
            Self::NwsFlashFloodGuidanceSystemNwsffgs => "NWS Flash Flood Guidance System (NWSFFGS)",
            Self::Wsr88dStageIiPrecipitationAnalysis => "WSR-88D Stage II Precipitation Analysis",
            Self::Wsr88dStageIiiPrecipitationAnalysis => "WSR-88D Stage III Precipitation Analysis",
            Self::QuantitativePrecipitationForecastGeneratedByNcep => "Quantitative Precipitation Forecast generated by NCEP",
            Self::RiverForecastCenterQuantitativePrecipitationForecastMosaicGeneratedByNcep => "River Forecast Center Quantitative Precipitation Forecast mosaic generated by NCEP",
            Self::RiverForecastCenterQuantitativePrecipitationEstimateMosaicGeneratedByNcep => "River Forecast Center Quantitative Precipitation estimate mosaic generated by NCEP",
            Self::NdfdProductGeneratedByNcepHpc => "NDFD product generated by NCEP/HPC",
            Self::ClimatologicalCalibratedPrecipitationAnalysisCcpa => "Climatological Calibrated Precipitation Analysis (CCPA)",
            Self::NationalConvectiveWeatherDiagnosticGeneratedByNcepAwc => "National Convective Weather Diagnostic generated by NCEP/AWC",
            Self::CurrentIcingPotentialAutomatedProductGeneratedByNcepAwc => "Current Icing Potential automated product generated by NCEP/AWC",
            Self::AnalysisProductFromNcepAwc => "Analysis product from NCEP/AWC",
            Self::ForecastProductFromNcepAwc => "Forecast product from NCEP/AWC",
            Self::ClimateDataAssimilationSystem2Cdas2 => "Climate Data Assimilation System 2 (CDAS2)",
            Self::ClimateDataAssimilationSystem2Cdas2UsedForRegenerationRuns => "Climate Data Assimilation System 2 (CDAS2) - used for regeneration runs",
            Self::ClimateDataAssimilationSystemCdas => "Climate Data Assimilation System (CDAS)",
            Self::ClimateDataAssimilationSystemCdasUsedForRegenerationRuns => "Climate Data Assimilation System (CDAS) - used for regeneration runs",
            Self::ClimateForecastSystemReanalysisCfsr => "Climate Forecast System Reanalysis (CFSR) -- Atmospheric model (GFS) coupled to a multi level ocean, land and seaice model. GFS spectral model at T382, 64 levels coupled to 40 level MOM4 ocean model.",
            Self::CpcManualForecastProduct => "CPC Manual Forecast Product",
            Self::CpcAutomatedProduct => "CPC Automated Product",
            Self::EpaAirQualityForecastNorthEastUsDomain => "EPA Air Quality Forecast - Currently North East US domain",
            Self::EpaAirQualityForecastEasternUsDomain => "EPA Air Quality Forecast - Currently Eastern US domain",
            Self::SpcManualForecastProduct => "SPC Manual Forecast Product",
            Self::NcepOpcAutomatedProduct => "NCEP/OPC automated product",
            Self::Missing => "Missing",
        };
        f.write_str(desc)
    }
}

/// # ON388 - TABLE C - NATIONAL SUB-CENTERS (Assigned By The Nation)
///
/// **Details**:
/// - **Originating Center**: 7 (US-NWS, NCEP)
/// - **GRIB1 - PDS Octet**: 26
/// - **GRIB2 - Section**: 1, Octets 8-9
/// - **Revised**: 02/23/2024
///
/// **Reserved Ranges**:
/// - `0`: Reserved
/// - `19-254`: Reserved
///
/// **Special Value**:
/// - `255`: Missing
///
/// ## Description
/// This table defines the national sub-centers assigned by Originating Center 7 (US-NWS, NCEP) in GRIB1 and GRIB2 files,
/// specifying various generating processes or models.
///
/// ## Notes
/// - Red text depicts changes made since 06/25/2019
#[repr(u8)]
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Grib2TableC {
    NcepReAnalysisProject = 1,
    NcepEnsembleProducts = 2,
    NcepCentralOperations = 3,
    EnvironmentalModelingCenter = 4,
    WeatherPredictionCenter = 5,
    OceanPredictionCenter = 6,
    ClimatePredictionCenter = 7,
    AviationWeatherCenter = 8,
    StormPredictionCenter = 9,
    NationalHurricaneCenter = 10,
    NwsTechniquesDevelopmentLaboratory = 11,
    NesdisOfficeOfResearchAndApplications = 12,
    FederalAviationAdministration = 13,
    NwsMeteorologicalDevelopmentLaboratory = 14,
    NorthAmericanRegionalReanalysisProject = 15,
    SpaceWeatherPredictionCenter = 16,
    EsrlGlobalSystemsDivision = 17,
    NationalWaterCenter = 18,
    Missing = 255,
}
impl From<u8> for Grib2TableC {
    fn from(val: u8) -> Self {
        match val {
            1 => Self::NcepReAnalysisProject,
            2 => Self::NcepEnsembleProducts,
            3 => Self::NcepCentralOperations,
            4 => Self::EnvironmentalModelingCenter,
            5 => Self::WeatherPredictionCenter,
            6 => Self::OceanPredictionCenter,
            7 => Self::ClimatePredictionCenter,
            8 => Self::AviationWeatherCenter,
            9 => Self::StormPredictionCenter,
            10 => Self::NationalHurricaneCenter,
            11 => Self::NwsTechniquesDevelopmentLaboratory,
            12 => Self::NesdisOfficeOfResearchAndApplications,
            13 => Self::FederalAviationAdministration,
            14 => Self::NwsMeteorologicalDevelopmentLaboratory,
            15 => Self::NorthAmericanRegionalReanalysisProject,
            16 => Self::SpaceWeatherPredictionCenter,
            17 => Self::EsrlGlobalSystemsDivision,
            18 => Self::NationalWaterCenter,
            _ => Self::Missing,
        }
    }
}
impl core::fmt::Display for Grib2TableC {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let desc = match self {
            Self::NcepReAnalysisProject => "NCEP Re-Analysis Project",
            Self::NcepEnsembleProducts => "NCEP Ensemble Products",
            Self::NcepCentralOperations => "NCEP Central Operations",
            Self::EnvironmentalModelingCenter => "Environmental Modeling Center",
            Self::WeatherPredictionCenter => "Weather Prediction Center",
            Self::OceanPredictionCenter => "Ocean Prediction Center",
            Self::ClimatePredictionCenter => "Climate Prediction Center",
            Self::AviationWeatherCenter => "Aviation Weather Center",
            Self::StormPredictionCenter => "Storm Prediction Center",
            Self::NationalHurricaneCenter => "National Hurricane Center",
            Self::NwsTechniquesDevelopmentLaboratory => "NWS Techniques Development Laboratory",
            Self::NesdisOfficeOfResearchAndApplications => {
                "NESDIS Office of Research and Applications"
            }
            Self::FederalAviationAdministration => "Federal Aviation Administration",
            Self::NwsMeteorologicalDevelopmentLaboratory => {
                "NWS Meteorological Development Laboratory"
            }
            Self::NorthAmericanRegionalReanalysisProject => {
                "North American Regional Reanalysis Project"
            }
            Self::SpaceWeatherPredictionCenter => "Space Weather Prediction Center",
            Self::EsrlGlobalSystemsDivision => "ESRL Global Systems Division",
            Self::NationalWaterCenter => "National Water Center",
            Self::Missing => "Missing",
        };
        f.write_str(desc)
    }
}
