[package]
name = "writers"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
# LOCAL dependencies
parsers = { path = "../parsers" }
util = { path = "../util" }
readers = { path = "../readers" }
geometry = { path = "../geometry" }
data_store = { path = "../data_store" }
data_structures = { path = "../data_structures" }
# OpenS2 dependencies
s2-tilejson = { workspace = true }
s2json = { workspace = true }
earclip = { workspace = true }
open-vector-tile = { workspace = true }
# External dependencies
libm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
# STD dependencies
memmap2 = { workspace = true, optional = true }

[dev-dependencies]
readers = { path = "../readers" }
tempfile = { workspace = true }

[features]
default = ["std"]
std = ["memmap2"]
