/// Table 0 - NATIONAL/INTERNATIONAL ORIGINATING CENTERS
///
/// [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/on388/table0.html)
#[repr(u8)]
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Grib2Table0 {
    MelbourneWMC1 = 1,
    MelbourneWMC2 = 2,
    MelbourneWMC3 = 3,
    MoscowWMC1 = 4,
    MoscowWMC2 = 5,
    MoscowWMC3 = 6,
    UsNationalWeatherServiceNcepWMC = 7,
    UsNationalWeatherServiceNwstgWMC = 8,
    UsNationalWeatherServiceOtherWMC = 9,
    CairoRsmcRafc1 = 10,
    CairoRsmcRafc2 = 11,
    DakarRsmcRafc1 = 12,
    DakarRsmcRafc2 = 13,
    NairobiRsmcRafc1 = 14,
    NairobiRsmcRafc2 = 15,
    CasablancaRsmc = 16,
    TunisRsmc = 17,
    TunisCasablancaRsmc1 = 18,
    TunisCasablancaRsmc2 = 19,
    LasPalmasRafc = 20,
    AlgiersRsmc = 21,
    Acmad = 22,
    MozambiqueNmc = 23,
    PretoriaRsmc = 24,
    LaReunionRsmc = 25,
    KhabarovskRsmc1 = 26,
    KhabarovskRsmc2 = 27,
    NewDelhiRsmcRafc1 = 28,
    NewDelhiRsmcRafc2 = 29,
    NovosibirskRsmc1 = 30,
    NovosibirskRsmc2 = 31,
    TashkentRsmc = 32,
    JeddahRsmc = 33,
    TokyoRsmcJapaneseMeteorologicalAgency1 = 34,
    TokyoRsmcJapaneseMeteorologicalAgency2 = 35,
    Bankok = 36,
    UlanBator = 37,
    BeijingRsmc1 = 38,
    BeijingRsmc2 = 39,
    Seoul = 40,
    BuenosAiresRsmcRafc1 = 41,
    BuenosAiresRsmcRafc2 = 42,
    BrasiliaRsmcRafc1 = 43,
    BrasiliaRsmcRafc2 = 44,
    Santiago = 45,
    BrazilianSpaceAgencyInpe = 46,
    ColumbiaNmc = 47,
    EcuadorNmc = 48,
    PeruNmc = 49,
    VenezuelaNmc = 50,
    MiamiRsmcRafc = 51,
    MiamiRsmcNationalHurricaneCenter = 52,
    CanadianMeteorologicalServiceMontrealRsmc1 = 53,
    CanadianMeteorologicalServiceMontrealRsmc2 = 54,
    SanFrancisco = 55,
    ArincCenter = 56,
    UsAirForceAirForceGlobalWeatherCenter = 57,
    FleetNumericalMeteorologyAndOceanographyCenterMontereyCaUsa = 58,
    TheNoaaForecastSystemsLabBoulderCoUsa = 59,
    NationalCenterForAtmosphericResearchNcarBoulderCo = 60,
    ServiceArgosLandoverMdUsa = 61,
    UsNavalOceanographicOffice = 62,
    InternationalResearchInstitudeForClimateAndSociety = 63,
    Honolulu = 64,
    DarwinRsmc1 = 65,
    DarwinRsmc2 = 66,
    MelbourneRsmc = 67,
    WellingtonRsmcRafc1 = 69,
    WellingtonRsmcRafc2 = 70,
    NadiRsmc = 71,
    Singapore = 72,
    MalaysiaNmc = 73,
    UkMetOfficeExeterRsmc1 = 74,
    UkMetOfficeExeterRsmc2 = 75,
    MoscowRsmcRafc = 76,
    OffenbachRsmc1 = 78,
    OffenbachRsmc2 = 79,
    RomeRsmc1 = 80,
    RomeRsmc2 = 81,
    Norrkoping1 = 82,
    Norrkoping2 = 83,
    FrenchWeatherServiceToulouse1 = 84,
    FrenchWeatherServiceToulouse2 = 85,
    Helsinki = 86,
    Belgrade = 87,
    Oslo = 88,
    Prague = 89,
    Episkopi = 90,
    Ankara = 91,
    FrankfurtMainRafc = 92,
    LondonWafc = 93,
    Copenhagen = 94,
    Rota = 95,
    Athens = 96,
    EuropeanSpaceAgencyEsa = 97,
    EuropeanCenterForMediumRangeWeatherForecastsRsmc = 98,
    DeBiltNetherlands = 99,
    Brazzaville = 100,
    Abidjan = 101,
    LibyanArabJamahiriyaNmc = 102,
    MadagascarNmc = 103,
    MauritiusNmc = 104,
    NigerNmc = 105,
    SeychellesNmc = 106,
    UgandaNmc = 107,
    UnitedRepublicOfTanzaniaNmc = 108,
    ZimbabweNmc = 109,
    HongKong = 110,
    AfghanistanNmc = 111,
    BahrainNmc = 112,
    BangladeshNmc = 113,
    BhutanNmc = 114,
    CambodiaNmc = 115,
    DemocraticPeoplesRepublicOfKoreaNmc = 116,
    IslamicRepublicOfIranNmc = 117,
    IraqNmc = 118,
    KazakhstanNmc = 119,
    KuwaitNmc = 120,
    KyrgyzRepublicNmc = 121,
    LaoPeoplesDemocraticRepublicNmc = 122,
    MacaoChina = 123,
    MaldivesNmc = 124,
    MyanmarNmc = 125,
    NepalNmc = 126,
    OmanNmc = 127,
    PakistanNmc = 128,
    QatarNmc = 129,
    YemenNmc = 130,
    SriLankaNmc = 131,
    TajikistanNmc = 132,
    TurkmenistanNmc = 133,
    UnitedArabEmiratesNmc = 134,
    UzbekistanNmc = 135,
    VietNamNmc = 136,
    BoliviaNmc = 140,
    GuyanaNmc = 141,
    ParaguayNmc = 142,
    SurinameNmc = 143,
    UruguayNmc = 144,
    FrenchGuyana = 145,
    BrazilianNavyHydrographicCenter = 146,
    NationalCommissionOnSpaceActivitiesArgentina = 147,
    BrazilianDepartmentOfAirspaceControlDecea = 148,
    AntiguaAndBarbudaNmc = 150,
    BahamasNmc = 151,
    BarbadosNmc = 152,
    BelizeNmc = 153,
    BritishCaribbeanTerritoriesCenter = 154,
    SanJose = 155,
    CubaNmc = 156,
    DominicaNmc = 157,
    DominicanRepublicNmc = 158,
    ElSalvadorNmc = 159,
    UsNoaaNesdis = 160,
    UsNoaaOfficeOfOceanicAndAtmosphericResearch = 161,
    GuatemalaNmc = 162,
    HaitiNmc = 163,
    HondurasNmc = 164,
    JamaicaNmc = 165,
    MexicoCity = 166,
    NetherlandsAntillesAndArubaNmc = 167,
    NicaraguaNmc = 168,
    PanamaNmc = 169,
    SaintLuciaNmc = 170,
    TrinidadAndTobagoNmc = 171,
    FrenchDepartmentsInRaIv = 172,
    UsNationalAeronauticsAndSpaceAdministrationNasa = 173,
    IntegratedSystemDataManagerMarineEnvironmentalDataServiceIsdmMedsCanada = 174,
    UsCooperativeInstitudeForMeteorologicalSatelliteStudies = 176,
    CookIslandsNmc = 190,
    FrenchPolynesiaNmc = 191,
    TongaNmc = 192,
    VanuatuNmc = 193,
    BruneiNmc = 194,
    IndonesiaNmc = 195,
    KiribatiNmc = 196,
    FederatedStatesOfMicronesiaNmc = 197,
    NewCaledoniaNmc = 198,
    Niue = 199,
    PapuaNewGuineaNmc = 200,
    PhilippinesNmc = 201,
    SamoaNmc = 202,
    SolomonIslandsNmc = 203,
    NarionalInstitudeOfWaterAndAtmosphericResearchNewZealand = 204,
    FrascatiEsaEsrin = 210,
    Lanion = 211,
    Lisbon = 212,
    Reykjavik = 213,
    Madrid = 214,
    Zurich = 215,
    ServiceArgosToulouse = 216,
    Bratislava = 217,
    Budapest = 218,
    Ljubljana = 219,
    Warsaw = 220,
    Zagreb = 221,
    AlbaniaNmc = 222,
    ArmeniaNmc = 223,
    AustriaNmc = 224,
    AzerbaijanNmc = 225,
    BelarusNmc = 226,
    BelgiumNmc = 227,
    BosniaAndHerzegovinaNmc = 228,
    BulgariaNmc = 229,
    CyprusNmc = 230,
    EstoniaNmc = 231,
    GeorgiaNmc = 232,
    Dublin = 233,
    IsraelNmc = 234,
    JordanNmc = 235,
    LatviaNmc = 236,
    LebanonNmc = 237,
    LithuaniaNmc = 238,
    Luxembourg = 239,
    MaltaNmc = 240,
    Monaco = 241,
    RomaniaNmc = 242,
    SyrianArabRepublicNmc = 243,
    TheFormerYugoslavRepublicOfMacedoniaNmc = 244,
    UkraineNmc = 245,
    RepublicOfMoldovaNmc = 246,
    OperationalProgrammeForTheExchangeOfWeatherRadarInformationOperaEumetnet = 247,
    ConsortiumForSmallScaleModellingCosmo = 250,
    EumetsatOperationsCenter = 254,
    MissingValue = 255,
}
impl From<u8> for Grib2Table0 {
    fn from(val: u8) -> Self {
        match val {
            1 => Self::MelbourneWMC1,
            2 => Self::MelbourneWMC2,
            3 => Self::MelbourneWMC3,
            4 => Self::MoscowWMC1,
            5 => Self::MoscowWMC2,
            6 => Self::MoscowWMC3,
            7 => Self::UsNationalWeatherServiceNcepWMC,
            8 => Self::UsNationalWeatherServiceNwstgWMC,
            9 => Self::UsNationalWeatherServiceOtherWMC,
            10 => Self::CairoRsmcRafc1,
            11 => Self::CairoRsmcRafc2,
            12 => Self::DakarRsmcRafc1,
            13 => Self::DakarRsmcRafc2,
            14 => Self::NairobiRsmcRafc1,
            15 => Self::NairobiRsmcRafc2,
            16 => Self::CasablancaRsmc,
            17 => Self::TunisRsmc,
            18 => Self::TunisCasablancaRsmc1,
            19 => Self::TunisCasablancaRsmc2,
            20 => Self::LasPalmasRafc,
            21 => Self::AlgiersRsmc,
            22 => Self::Acmad,
            23 => Self::MozambiqueNmc,
            24 => Self::PretoriaRsmc,
            25 => Self::LaReunionRsmc,
            26 => Self::KhabarovskRsmc1,
            27 => Self::KhabarovskRsmc2,
            28 => Self::NewDelhiRsmcRafc1,
            29 => Self::NewDelhiRsmcRafc2,
            30 => Self::NovosibirskRsmc1,
            31 => Self::NovosibirskRsmc2,
            32 => Self::TashkentRsmc,
            33 => Self::JeddahRsmc,
            34 => Self::TokyoRsmcJapaneseMeteorologicalAgency1,
            35 => Self::TokyoRsmcJapaneseMeteorologicalAgency2,
            36 => Self::Bankok,
            37 => Self::UlanBator,
            38 => Self::BeijingRsmc1,
            39 => Self::BeijingRsmc2,
            40 => Self::Seoul,
            41 => Self::BuenosAiresRsmcRafc1,
            42 => Self::BuenosAiresRsmcRafc2,
            43 => Self::BrasiliaRsmcRafc1,
            44 => Self::BrasiliaRsmcRafc2,
            45 => Self::Santiago,
            46 => Self::BrazilianSpaceAgencyInpe,
            47 => Self::ColumbiaNmc,
            48 => Self::EcuadorNmc,
            49 => Self::PeruNmc,
            50 => Self::VenezuelaNmc,
            51 => Self::MiamiRsmcRafc,
            52 => Self::MiamiRsmcNationalHurricaneCenter,
            53 => Self::CanadianMeteorologicalServiceMontrealRsmc1,
            54 => Self::CanadianMeteorologicalServiceMontrealRsmc2,
            55 => Self::SanFrancisco,
            56 => Self::ArincCenter,
            57 => Self::UsAirForceAirForceGlobalWeatherCenter,
            58 => Self::FleetNumericalMeteorologyAndOceanographyCenterMontereyCaUsa,
            59 => Self::TheNoaaForecastSystemsLabBoulderCoUsa,
            60 => Self::NationalCenterForAtmosphericResearchNcarBoulderCo,
            61 => Self::ServiceArgosLandoverMdUsa,
            62 => Self::UsNavalOceanographicOffice,
            63 => Self::InternationalResearchInstitudeForClimateAndSociety,
            64 => Self::Honolulu,
            65 => Self::DarwinRsmc1,
            66 => Self::DarwinRsmc2,
            67 => Self::MelbourneRsmc,
            69 => Self::WellingtonRsmcRafc1,
            70 => Self::WellingtonRsmcRafc2,
            71 => Self::NadiRsmc,
            72 => Self::Singapore,
            73 => Self::MalaysiaNmc,
            74 => Self::UkMetOfficeExeterRsmc1,
            75 => Self::UkMetOfficeExeterRsmc2,
            76 => Self::MoscowRsmcRafc,
            78 => Self::OffenbachRsmc1,
            79 => Self::OffenbachRsmc2,
            80 => Self::RomeRsmc1,
            81 => Self::RomeRsmc2,
            82 => Self::Norrkoping1,
            83 => Self::Norrkoping2,
            84 => Self::FrenchWeatherServiceToulouse1,
            85 => Self::FrenchWeatherServiceToulouse2,
            86 => Self::Helsinki,
            87 => Self::Belgrade,
            88 => Self::Oslo,
            89 => Self::Prague,
            90 => Self::Episkopi,
            91 => Self::Ankara,
            92 => Self::FrankfurtMainRafc,
            93 => Self::LondonWafc,
            94 => Self::Copenhagen,
            95 => Self::Rota,
            96 => Self::Athens,
            97 => Self::EuropeanSpaceAgencyEsa,
            98 => Self::EuropeanCenterForMediumRangeWeatherForecastsRsmc,
            99 => Self::DeBiltNetherlands,
            100 => Self::Brazzaville,
            101 => Self::Abidjan,
            102 => Self::LibyanArabJamahiriyaNmc,
            103 => Self::MadagascarNmc,
            104 => Self::MauritiusNmc,
            105 => Self::NigerNmc,
            106 => Self::SeychellesNmc,
            107 => Self::UgandaNmc,
            108 => Self::UnitedRepublicOfTanzaniaNmc,
            109 => Self::ZimbabweNmc,
            110 => Self::HongKong,
            111 => Self::AfghanistanNmc,
            112 => Self::BahrainNmc,
            113 => Self::BangladeshNmc,
            114 => Self::BhutanNmc,
            115 => Self::CambodiaNmc,
            116 => Self::DemocraticPeoplesRepublicOfKoreaNmc,
            117 => Self::IslamicRepublicOfIranNmc,
            118 => Self::IraqNmc,
            119 => Self::KazakhstanNmc,
            120 => Self::KuwaitNmc,
            121 => Self::KyrgyzRepublicNmc,
            122 => Self::LaoPeoplesDemocraticRepublicNmc,
            123 => Self::MacaoChina,
            124 => Self::MaldivesNmc,
            125 => Self::MyanmarNmc,
            126 => Self::NepalNmc,
            127 => Self::OmanNmc,
            128 => Self::PakistanNmc,
            129 => Self::QatarNmc,
            130 => Self::YemenNmc,
            131 => Self::SriLankaNmc,
            132 => Self::TajikistanNmc,
            133 => Self::TurkmenistanNmc,
            134 => Self::UnitedArabEmiratesNmc,
            135 => Self::UzbekistanNmc,
            136 => Self::VietNamNmc,
            140 => Self::BoliviaNmc,
            141 => Self::GuyanaNmc,
            142 => Self::ParaguayNmc,
            143 => Self::SurinameNmc,
            144 => Self::UruguayNmc,
            145 => Self::FrenchGuyana,
            146 => Self::BrazilianNavyHydrographicCenter,
            147 => Self::NationalCommissionOnSpaceActivitiesArgentina,
            148 => Self::BrazilianDepartmentOfAirspaceControlDecea,
            150 => Self::AntiguaAndBarbudaNmc,
            151 => Self::BahamasNmc,
            152 => Self::BarbadosNmc,
            153 => Self::BelizeNmc,
            154 => Self::BritishCaribbeanTerritoriesCenter,
            155 => Self::SanJose,
            156 => Self::CubaNmc,
            157 => Self::DominicaNmc,
            158 => Self::DominicanRepublicNmc,
            159 => Self::ElSalvadorNmc,
            160 => Self::UsNoaaNesdis,
            161 => Self::UsNoaaOfficeOfOceanicAndAtmosphericResearch,
            162 => Self::GuatemalaNmc,
            163 => Self::HaitiNmc,
            164 => Self::HondurasNmc,
            165 => Self::JamaicaNmc,
            166 => Self::MexicoCity,
            167 => Self::NetherlandsAntillesAndArubaNmc,
            168 => Self::NicaraguaNmc,
            169 => Self::PanamaNmc,
            170 => Self::SaintLuciaNmc,
            171 => Self::TrinidadAndTobagoNmc,
            172 => Self::FrenchDepartmentsInRaIv,
            173 => Self::UsNationalAeronauticsAndSpaceAdministrationNasa,
            174 => Self::IntegratedSystemDataManagerMarineEnvironmentalDataServiceIsdmMedsCanada,
            176 => Self::UsCooperativeInstitudeForMeteorologicalSatelliteStudies,
            190 => Self::CookIslandsNmc,
            191 => Self::FrenchPolynesiaNmc,
            192 => Self::TongaNmc,
            193 => Self::VanuatuNmc,
            194 => Self::BruneiNmc,
            195 => Self::IndonesiaNmc,
            196 => Self::KiribatiNmc,
            197 => Self::FederatedStatesOfMicronesiaNmc,
            198 => Self::NewCaledoniaNmc,
            199 => Self::Niue,
            200 => Self::PapuaNewGuineaNmc,
            201 => Self::PhilippinesNmc,
            202 => Self::SamoaNmc,
            203 => Self::SolomonIslandsNmc,
            204 => Self::NarionalInstitudeOfWaterAndAtmosphericResearchNewZealand,
            210 => Self::FrascatiEsaEsrin,
            211 => Self::Lanion,
            212 => Self::Lisbon,
            213 => Self::Reykjavik,
            214 => Self::Madrid,
            215 => Self::Zurich,
            216 => Self::ServiceArgosToulouse,
            217 => Self::Bratislava,
            218 => Self::Budapest,
            219 => Self::Ljubljana,
            220 => Self::Warsaw,
            221 => Self::Zagreb,
            222 => Self::AlbaniaNmc,
            223 => Self::ArmeniaNmc,
            224 => Self::AustriaNmc,
            225 => Self::AzerbaijanNmc,
            226 => Self::BelarusNmc,
            227 => Self::BelgiumNmc,
            228 => Self::BosniaAndHerzegovinaNmc,
            229 => Self::BulgariaNmc,
            230 => Self::CyprusNmc,
            231 => Self::EstoniaNmc,
            232 => Self::GeorgiaNmc,
            233 => Self::Dublin,
            234 => Self::IsraelNmc,
            235 => Self::JordanNmc,
            236 => Self::LatviaNmc,
            237 => Self::LebanonNmc,
            238 => Self::LithuaniaNmc,
            239 => Self::Luxembourg,
            240 => Self::MaltaNmc,
            241 => Self::Monaco,
            242 => Self::RomaniaNmc,
            243 => Self::SyrianArabRepublicNmc,
            244 => Self::TheFormerYugoslavRepublicOfMacedoniaNmc,
            245 => Self::UkraineNmc,
            246 => Self::RepublicOfMoldovaNmc,
            247 => Self::OperationalProgrammeForTheExchangeOfWeatherRadarInformationOperaEumetnet,
            250 => Self::ConsortiumForSmallScaleModellingCosmo,
            254 => Self::EumetsatOperationsCenter,
            _ => Self::MissingValue,
        }
    }
}
impl core::fmt::Display for Grib2Table0 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let desc = match self {
            Self::MelbourneWMC1 => "Melbourne (WMC)",
            Self::MelbourneWMC2 => "Melbourne (WMC)",
            Self::MelbourneWMC3 => "Melbourne (WMC)",
            Self::MoscowWMC1 => "Moscow (WMC)",
            Self::MoscowWMC2 => "Moscow (WMC)",
            Self::MoscowWMC3 => "Moscow (WMC)",
            Self::UsNationalWeatherServiceNcepWMC => "US National Weather Service - NCEP (WMC)",
            Self::UsNationalWeatherServiceNwstgWMC => "US National Weather Service - NWSTG (WMC)",
            Self::UsNationalWeatherServiceOtherWMC => "US National Weather Service - Other (WMC)",
            Self::CairoRsmcRafc1 => "Cairo (RSMC/RAFC)",
            Self::CairoRsmcRafc2 => "Cairo (RSMC/RAFC)",
            Self::DakarRsmcRafc1 => "Dakar (RSMC/RAFC)",
            Self::DakarRsmcRafc2 => "Dakar (RSMC/RAFC)",
            Self::NairobiRsmcRafc1 => "Nairobi (RSMC/RAFC)",
            Self::NairobiRsmcRafc2 => "Nairobi (RSMC/RAFC)",
            Self::CasablancaRsmc => "Casablanca (RSMC)",
            Self::TunisRsmc => "Tunis (RSMC)",
            Self::TunisCasablancaRsmc1 => "Tunis-Casablanca (RSMC)",
            Self::TunisCasablancaRsmc2 => "Tunis-Casablanca (RSMC)",
            Self::LasPalmasRafc => "Las Palmas (RAFC)",
            Self::AlgiersRsmc => "Algiers (RSMC)",
            Self::Acmad => "ACMAD",
            Self::MozambiqueNmc => "Mozambique (NMC)",
            Self::PretoriaRsmc => "Pretoria (RSMC)",
            Self::LaReunionRsmc => "La Reunion (RSMC)",
            Self::KhabarovskRsmc1 => "Khabarovsk (RSMC)",
            Self::KhabarovskRsmc2 => "Khabarovsk (RSMC)",
            Self::NewDelhiRsmcRafc1 => "New Delhi (RSMC/RAFC)",
            Self::NewDelhiRsmcRafc2 => "New Delhi (RSMC/RAFC)",
            Self::NovosibirskRsmc1 => "Novosibirsk (RSMC)",
            Self::NovosibirskRsmc2 => "Novosibirsk (RSMC)",
            Self::TashkentRsmc => "Tashkent (RSMC)",
            Self::JeddahRsmc => "Jeddah (RSMC)",
            Self::TokyoRsmcJapaneseMeteorologicalAgency1 => {
                "Tokyo (RSMC), Japanese Meteorological Agency"
            }
            Self::TokyoRsmcJapaneseMeteorologicalAgency2 => {
                "Tokyo (RSMC), Japanese Meteorological Agency"
            }
            Self::Bankok => "Bankok",
            Self::UlanBator => "Ulan Bator",
            Self::BeijingRsmc1 => "Beijing (RSMC)",
            Self::BeijingRsmc2 => "Beijing (RSMC)",
            Self::Seoul => "Seoul",
            Self::BuenosAiresRsmcRafc1 => "Buenos Aires (RSMC/RAFC)",
            Self::BuenosAiresRsmcRafc2 => "Buenos Aires (RSMC/RAFC)",
            Self::BrasiliaRsmcRafc1 => "Brasilia (RSMC/RAFC)",
            Self::BrasiliaRsmcRafc2 => "Brasilia (RSMC/RAFC)",
            Self::Santiago => "Santiago",
            Self::BrazilianSpaceAgencyInpe => "Brazilian Space Agency - INPE",
            Self::ColumbiaNmc => "Columbia (NMC)",
            Self::EcuadorNmc => "Ecuador (NMC)",
            Self::PeruNmc => "Peru (NMC)",
            Self::VenezuelaNmc => "Venezuela (NMC)",
            Self::MiamiRsmcRafc => "Miami (RSMC/RAFC)",
            Self::MiamiRsmcNationalHurricaneCenter => "Miami (RSMC), National Hurricane Center",
            Self::CanadianMeteorologicalServiceMontrealRsmc1 => {
                "Canadian Meteorological Service - Montreal (RSMC)"
            }
            Self::CanadianMeteorologicalServiceMontrealRsmc2 => {
                "Canadian Meteorological Service - Montreal (RSMC)"
            }
            Self::SanFrancisco => "San Francisco",
            Self::ArincCenter => "ARINC Center",
            Self::UsAirForceAirForceGlobalWeatherCenter => {
                "US Air Force - Air Force Global Weather Center"
            }
            Self::FleetNumericalMeteorologyAndOceanographyCenterMontereyCaUsa => {
                "Fleet Numerical Meteorology and Oceanography Center,Monterey,CA,USA"
            }
            Self::TheNoaaForecastSystemsLabBoulderCoUsa => {
                "The NOAA Forecast Systems Lab, Boulder, CO, USA"
            }
            Self::NationalCenterForAtmosphericResearchNcarBoulderCo => {
                "National Center for Atmospheric Research (NCAR), Boulder, CO"
            }
            Self::ServiceArgosLandoverMdUsa => "Service ARGOS - Landover, MD, USA",
            Self::UsNavalOceanographicOffice => "US Naval Oceanographic Office",
            Self::InternationalResearchInstitudeForClimateAndSociety => {
                "International Research Institude for Climate and Society"
            }
            Self::Honolulu => "Honolulu",
            Self::DarwinRsmc1 => "Darwin (RSMC)",
            Self::DarwinRsmc2 => "Darwin (RSMC)",
            Self::MelbourneRsmc => "Melbourne (RSMC)",
            Self::WellingtonRsmcRafc1 => "Wellington (RSMC/RAFC)",
            Self::WellingtonRsmcRafc2 => "Wellington (RSMC/RAFC)",
            Self::NadiRsmc => "Nadi (RSMC)",
            Self::Singapore => "Singapore",
            Self::MalaysiaNmc => "Malaysia (NMC)",
            Self::UkMetOfficeExeterRsmc1 => "U.K. Met Office - Exeter (RSMC)",
            Self::UkMetOfficeExeterRsmc2 => "U.K. Met Office - Exeter (RSMC)",
            Self::MoscowRsmcRafc => "Moscow (RSMC/RAFC)",
            Self::OffenbachRsmc1 => "Offenbach (RSMC)",
            Self::OffenbachRsmc2 => "Offenbach (RSMC)",
            Self::RomeRsmc1 => "Rome (RSMC)",
            Self::RomeRsmc2 => "Rome (RSMC)",
            Self::Norrkoping1 => "Norrkoping",
            Self::Norrkoping2 => "Norrkoping",
            Self::FrenchWeatherServiceToulouse1 => "French Weather Service - Toulouse",
            Self::FrenchWeatherServiceToulouse2 => "French Weather Service - Toulouse",
            Self::Helsinki => "Helsinki",
            Self::Belgrade => "Belgrade",
            Self::Oslo => "Oslo",
            Self::Prague => "Prague",
            Self::Episkopi => "Episkopi",
            Self::Ankara => "Ankara",
            Self::FrankfurtMainRafc => "Frankfurt/Main (RAFC)",
            Self::LondonWafc => "London (WAFC)",
            Self::Copenhagen => "Copenhagen",
            Self::Rota => "Rota",
            Self::Athens => "Athens",
            Self::EuropeanSpaceAgencyEsa => "European Space Agency (ESA)",
            Self::EuropeanCenterForMediumRangeWeatherForecastsRsmc => {
                "European Center for Medium-Range Weather Forecasts (RSMC)"
            }
            Self::DeBiltNetherlands => "De Bilt, Netherlands",
            Self::Brazzaville => "Brazzaville",
            Self::Abidjan => "Abidjan",
            Self::LibyanArabJamahiriyaNmc => "Libyan Arab Jamahiriya (NMC)",
            Self::MadagascarNmc => "Madagascar (NMC)",
            Self::MauritiusNmc => "Mauritius (NMC)",
            Self::NigerNmc => "Niger (NMC)",
            Self::SeychellesNmc => "Seychelles (NMC)",
            Self::UgandaNmc => "Uganda (NMC)",
            Self::UnitedRepublicOfTanzaniaNmc => "United Republic of Tanzania (NMC)",
            Self::ZimbabweNmc => "Zimbabwe (NMC)",
            Self::HongKong => "Hong-Kong",
            Self::AfghanistanNmc => "Afghanistan (NMC)",
            Self::BahrainNmc => "Bahrain (NMC)",
            Self::BangladeshNmc => "Bangladesh (NMC)",
            Self::BhutanNmc => "Bhutan (NMC)",
            Self::CambodiaNmc => "Cambodia (NMC)",
            Self::DemocraticPeoplesRepublicOfKoreaNmc => {
                "Democratic People's Republic of Korea (NMC)"
            }
            Self::IslamicRepublicOfIranNmc => "Islamic Republic of Iran (NMC)",
            Self::IraqNmc => "Iraq (NMC)",
            Self::KazakhstanNmc => "Kazakhstan (NMC)",
            Self::KuwaitNmc => "Kuwait (NMC)",
            Self::KyrgyzRepublicNmc => "Kyrgyz Republic (NMC)",
            Self::LaoPeoplesDemocraticRepublicNmc => "Lao People's Democratic Republic (NMC)",
            Self::MacaoChina => "Macao, China",
            Self::MaldivesNmc => "Maldives (NMC)",
            Self::MyanmarNmc => "Myanmar (NMC)",
            Self::NepalNmc => "Nepal (NMC)",
            Self::OmanNmc => "Oman (NMC)",
            Self::PakistanNmc => "Pakistan (NMC)",
            Self::QatarNmc => "Qatar (NMC)",
            Self::YemenNmc => "Yemen (NMC)",
            Self::SriLankaNmc => "Sri Lanka (NMC)",
            Self::TajikistanNmc => "Tajikistan (NMC)",
            Self::TurkmenistanNmc => "Turkmenistan (NMC)",
            Self::UnitedArabEmiratesNmc => "United Arab Emirates (NMC)",
            Self::UzbekistanNmc => "Uzbekistan (NMC)",
            Self::VietNamNmc => "Viet Nam (NMC)",
            Self::BoliviaNmc => "Bolivia (NMC)",
            Self::GuyanaNmc => "Guyana (NMC)",
            Self::ParaguayNmc => "Paraguay (NMC)",
            Self::SurinameNmc => "Suriname (NMC)",
            Self::UruguayNmc => "Uruguay (NMC)",
            Self::FrenchGuyana => "French Guyana",
            Self::BrazilianNavyHydrographicCenter => "Brazilian Navy Hydrographic Center",
            Self::NationalCommissionOnSpaceActivitiesArgentina => {
                "National Commission on Space Activities - Argentina"
            }
            Self::BrazilianDepartmentOfAirspaceControlDecea => {
                "Brazilian Department of Airspace Control - DECEA"
            }
            Self::AntiguaAndBarbudaNmc => "Antigua and Barbuda (NMC)",
            Self::BahamasNmc => "Bahamas (NMC)",
            Self::BarbadosNmc => "Barbados (NMC)",
            Self::BelizeNmc => "Belize (NMC)",
            Self::BritishCaribbeanTerritoriesCenter => "British Caribbean Territories Center",
            Self::SanJose => "San Jose",
            Self::CubaNmc => "Cuba (NMC)",
            Self::DominicaNmc => "Dominica (NMC)",
            Self::DominicanRepublicNmc => "Dominican Republic (NMC)",
            Self::ElSalvadorNmc => "El Salvador (NMC)",
            Self::UsNoaaNesdis => "US NOAA/NESDIS",
            Self::UsNoaaOfficeOfOceanicAndAtmosphericResearch => {
                "US NOAA Office of Oceanic and Atmospheric Research"
            }
            Self::GuatemalaNmc => "Guatemala (NMC)",
            Self::HaitiNmc => "Haiti (NMC)",
            Self::HondurasNmc => "Honduras (NMC)",
            Self::JamaicaNmc => "Jamaica (NMC)",
            Self::MexicoCity => "Mexico City",
            Self::NetherlandsAntillesAndArubaNmc => "Netherlands Antilles and Aruba (NMC)",
            Self::NicaraguaNmc => "Nicaragua (NMC)",
            Self::PanamaNmc => "Panama (NMC)",
            Self::SaintLuciaNmc => "Saint Lucia (NMC)",
            Self::TrinidadAndTobagoNmc => "Trinidad and Tobago (NMC)",
            Self::FrenchDepartmentsInRaIv => "French Departments in RA IV",
            Self::UsNationalAeronauticsAndSpaceAdministrationNasa => {
                "US National Aeronautics and Space Administration (NASA)"
            }
            Self::IntegratedSystemDataManagerMarineEnvironmentalDataServiceIsdmMedsCanada => {
                "Integrated System Data Management/Marine Environmental Data Service (ISDM/MEDS) - \
                 Canada"
            }
            Self::UsCooperativeInstitudeForMeteorologicalSatelliteStudies => {
                "US Cooperative Institude for Meteorological Satellite Studies"
            }
            Self::CookIslandsNmc => "Cook Islands (NMC)",
            Self::FrenchPolynesiaNmc => "French Polynesia (NMC)",
            Self::TongaNmc => "Tonga (NMC)",
            Self::VanuatuNmc => "Vanuatu (NMC)",
            Self::BruneiNmc => "Brunei (NMC)",
            Self::IndonesiaNmc => "Indonesia (NMC)",
            Self::KiribatiNmc => "Kiribati (NMC)",
            Self::FederatedStatesOfMicronesiaNmc => "Federated States of Micronesia (NMC)",
            Self::NewCaledoniaNmc => "New Caledonia (NMC)",
            Self::Niue => "Niue",
            Self::PapuaNewGuineaNmc => "Papua New Guinea (NMC)",
            Self::PhilippinesNmc => "Philippines (NMC)",
            Self::SamoaNmc => "Samoa (NMC)",
            Self::SolomonIslandsNmc => "Solomon Islands (NMC)",
            Self::NarionalInstitudeOfWaterAndAtmosphericResearchNewZealand => {
                "Narional Institude of Water and Atmospheric Research - New Zealand"
            }
            Self::FrascatiEsaEsrin => "Frascati (ESA/ESRIN)",
            Self::Lanion => "Lanion",
            Self::Lisbon => "Lisbon",
            Self::Reykjavik => "Reykjavik",
            Self::Madrid => "Madrid",
            Self::Zurich => "Zurich",
            Self::ServiceArgosToulouse => "Service ARGOS - Toulouse",
            Self::Bratislava => "Bratislava",
            Self::Budapest => "Budapest",
            Self::Ljubljana => "Ljubljana",
            Self::Warsaw => "Warsaw",
            Self::Zagreb => "Zagreb",
            Self::AlbaniaNmc => "Albania (NMC)",
            Self::ArmeniaNmc => "Armenia (NMC)",
            Self::AustriaNmc => "Austria (NMC)",
            Self::AzerbaijanNmc => "Azerbaijan (NMC)",
            Self::BelarusNmc => "Belarus (NMC)",
            Self::BelgiumNmc => "Belgium (NMC)",
            Self::BosniaAndHerzegovinaNmc => "Bosnia and Herzegovina (NMC)",
            Self::BulgariaNmc => "Bulgaria (NMC)",
            Self::CyprusNmc => "Cyprus (NMC)",
            Self::EstoniaNmc => "Estonia (NMC)",
            Self::GeorgiaNmc => "Georgia (NMC)",
            Self::Dublin => "Dublin",
            Self::IsraelNmc => "Israel (NMC)",
            Self::JordanNmc => "Jordan (NMC)",
            Self::LatviaNmc => "Latvia (NMC)",
            Self::LebanonNmc => "Lebanon (NMC)",
            Self::LithuaniaNmc => "Lithuania (NMC)",
            Self::Luxembourg => "Luxembourg",
            Self::MaltaNmc => "Malta (NMC)",
            Self::Monaco => "Monaco",
            Self::RomaniaNmc => "Romania (NMC)",
            Self::SyrianArabRepublicNmc => "Syrian Arab Republic (NMC)",
            Self::TheFormerYugoslavRepublicOfMacedoniaNmc => {
                "The former Yugoslav Republic of Macedonia (NMC)"
            }
            Self::UkraineNmc => "Ukraine (NMC)",
            Self::RepublicOfMoldovaNmc => "Republic of Moldova (NMC)",
            Self::OperationalProgrammeForTheExchangeOfWeatherRadarInformationOperaEumetnet => {
                "Operational Programme for the Exchange of Weather RAdar Information (OPERA) - \
                 EUMETNET"
            }
            Self::ConsortiumForSmallScaleModellingCosmo => {
                "COnsortium for Small scale  MOdelling (COSMO)"
            }
            Self::EumetsatOperationsCenter => "EUMETSAT Operations Center",
            Self::MissingValue => "Missing Value",
        };
        f.write_str(desc)
    }
}

///  TABLE 0.0 - Discipline of Processed Data
///
/// [Read more...](https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table0-0.shtml)
/// This table is used to indicate the discipline of the processed data contained within a GRIB message.
/// This number is coded in octet 7 of section 0 of the GRIB2 message.
#[repr(u8)]
#[allow(missing_docs)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Grib2Table0_0 {
    Meteorological = 0,
    Hydrological = 1,
    LandSurface = 2,
    SatelliteRemoteSensing = 3,
    SpaceWeather = 4,
    Oceanographic = 10,
    Unknown(u8),
}
impl From<u8> for Grib2Table0_0 {
    fn from(val: u8) -> Self {
        match val {
            0 => Self::Meteorological,
            1 => Self::Hydrological,
            2 => Self::LandSurface,
            3 => Self::SatelliteRemoteSensing,
            4 => Self::SpaceWeather,
            10 => Self::Oceanographic,
            other => Self::Unknown(other),
        }
    }
}
impl From<Grib2Table0_0> for u8 {
    fn from(val: Grib2Table0_0) -> Self {
        match val {
            Grib2Table0_0::Meteorological => 0,
            Grib2Table0_0::Hydrological => 1,
            Grib2Table0_0::LandSurface => 2,
            Grib2Table0_0::SatelliteRemoteSensing => 3,
            Grib2Table0_0::SpaceWeather => 4,
            Grib2Table0_0::Oceanographic => 10,
            Grib2Table0_0::Unknown(v) => v,
        }
    }
}
impl core::fmt::Display for Grib2Table0_0 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let desc = match self {
            Self::Meteorological => "Meteorological Products",
            Self::Hydrological => "Hydrological Products",
            Self::LandSurface => "Land Surface Products",
            Self::SatelliteRemoteSensing => "Satellite Remote Sensing Products",
            Self::SpaceWeather => "Space Weather Products",
            Self::Oceanographic => "Oceanographic Products",
            Self::Unknown(v) => return write!(f, "Unknown Discipline ({v})"),
        };
        f.write_str(desc)
    }
}
