import { buildGTFSSchedule, parseGTFSAttributions } from '../../../src';
import { expect, test } from 'bun:test';

// TODO:
// - [ ] pull all geometry features
// - [ ] areas
// - [ ] bookingRules
// - [ ] fareLegJoinRules
// - [ ] fareLegRules
// - [ ] fareMedia
// - [ ] fareProducts
// - [ ] fareTransferRules
// - [ ] feedInfo
// - [ ] frequencies
// - [ ] levels
// - [ ] locationGroupStops
// - [ ] networks
// - [ ] pathways
// - [ ] routeNetworks
// - [ ] stopAreas
// - [ ] timeframes
// - [ ] transfers
// - [ ] translations

test('attributions', async () => {
  const attributions = parseGTFSAttributions(
    await Bun.file(`${__dirname}/fixtures/attributions.csv`).text(),
  );
  expect(attributions).toEqual({
    Rejseplanen: {
      agencyId: undefined,
      attributionEmail: undefined,
      attributionPhone: undefined,
      attributionUrl: 'https://www.rejseplanen.dk',
      id: 'rp',
      isAuthority: 0,
      isOperator: 0,
      isProducer: 1,
      organizationName: 'Rejseplanen',
      routeId: undefined,
      tripId: undefined,
    },
  });
});

test('build schedule', async () => {
  const schedule = await buildGTFSSchedule(
    await Bun.file(`${__dirname}/fixtures/caltrain_20160406.zip`).arrayBuffer(),
  );
  expect(schedule).toBeDefined();
  expect(Object.keys(schedule)).toEqual([
    'agencies',
    'areas',
    'attributions',
    'bookingRules',
    'calendar',
    'calendarDates',
    'fareAttributes',
    'fareLegJoinRules',
    'fareLegRules',
    'fareMedia',
    'fareProducts',
    'fareRules',
    'fareTransferRules',
    'feedInfo',
    'frequencies',
    'levels',
    'locationGroups',
    'locationGroupStops',
    'networks',
    'pathways',
    'routeNetworks',
    'routes',
    'shapes',
    'stopAreas',
    'stops',
    'stopTimes',
    'timeframes',
    'transfers',
    'translations',
    'trips',
    'geojson',
  ]);

  expect(schedule.agencies).toEqual({
    CT: {
      email: undefined,
      fareURL: undefined,
      id: 'CT',
      lang: 'en',
      name: 'Caltrain',
      phone: '800-660-4287',
      timezone: 'America/Los_Angeles',
      url: 'http://www.caltrain.com',
    },
  });

  expect(schedule.calendarDates).toEqual([
    {
      date: new Date('2016-05-30T00:00:00.000Z'),
      exceptionType: 2,
      serviceId: 'CT-16APR-Caltrain-Weekday-01',
    },
    {
      date: new Date('2016-05-30T00:00:00.000Z'),
      exceptionType: 1,
      serviceId: 'CT-16APR-Caltrain-Sunday-02',
    },
    {
      date: new Date('2016-07-04T00:00:00.000Z'),
      exceptionType: 2,
      serviceId: 'CT-16APR-Caltrain-Weekday-01',
    },
    {
      date: new Date('2016-07-04T00:00:00.000Z'),
      exceptionType: 1,
      serviceId: 'CT-16APR-Caltrain-Sunday-02',
    },
    {
      date: new Date('2016-09-05T00:00:00.000Z'),
      exceptionType: 2,
      serviceId: 'CT-16APR-Caltrain-Weekday-01',
    },
    {
      date: new Date('2016-09-05T00:00:00.000Z'),
      exceptionType: 1,
      serviceId: 'CT-16APR-Caltrain-Sunday-02',
    },
    {
      date: new Date('2016-11-24T00:00:00.000Z'),
      exceptionType: 2,
      serviceId: 'CT-16APR-Caltrain-Weekday-01',
    },
    {
      date: new Date('2016-11-24T00:00:00.000Z'),
      exceptionType: 1,
      serviceId: 'CT-16APR-Caltrain-Sunday-02',
    },
  ]);

  expect(schedule.calendar).toEqual([
    {
      endDate: new Date('2019-03-31T00:00:00.000Z'),
      friday: 1,
      monday: 1,
      saturday: 0,
      serviceId: 'CT-16APR-Caltrain-Weekday-01',
      startDate: new Date('2016-04-04T00:00:00.000Z'),
      sunday: 0,
      thursday: 1,
      tuesday: 1,
      wednesday: 1,
    },
    {
      endDate: new Date('2019-03-31T00:00:00.000Z'),
      friday: 0,
      monday: 0,
      saturday: 1,
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      startDate: new Date('2014-03-29T00:00:00.000Z'),
      sunday: 0,
      thursday: 0,
      tuesday: 0,
      wednesday: 0,
    },
    {
      endDate: new Date('2019-03-31T00:00:00.000Z'),
      friday: 0,
      monday: 0,
      saturday: 0,
      serviceId: 'CT-16APR-Caltrain-Sunday-02',
      startDate: new Date('2014-03-23T00:00:00.000Z'),
      sunday: 1,
      thursday: 0,
      tuesday: 0,
      wednesday: 0,
    },
  ]);

  expect(schedule.fareAttributes).toEqual({
    OW_1_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_1_20160228',
      paymentMethod: 1,
      price: 3.75,
      transferDuration: undefined,
      transfers: 0,
    },
    OW_2_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_2_20160228',
      paymentMethod: 1,
      price: 5.75,
      transferDuration: undefined,
      transfers: 0,
    },
    OW_3_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_3_20160228',
      paymentMethod: 1,
      price: 7.75,
      transferDuration: undefined,
      transfers: 0,
    },
    OW_4_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_4_20160228',
      paymentMethod: 1,
      price: 9.75,
      transferDuration: undefined,
      transfers: 0,
    },
    OW_5_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_5_20160228',
      paymentMethod: 1,
      price: 11.75,
      transferDuration: undefined,
      transfers: 0,
    },
    OW_6_20160228: {
      agencyId: undefined,
      currencyType: 'USD',
      id: 'OW_6_20160228',
      paymentMethod: 1,
      price: 13.75,
      transferDuration: undefined,
      transfers: 0,
    },
  });

  expect(schedule.fareRules?.length).toEqual(144);
  expect(schedule.fareRules?.slice(0, 10)).toEqual([
    {
      containsId: undefined,
      destinationId: '1',
      fareId: 'OW_1_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '2',
      fareId: 'OW_2_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '3',
      fareId: 'OW_3_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '4',
      fareId: 'OW_4_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '5',
      fareId: 'OW_5_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '6',
      fareId: 'OW_6_20160228',
      originId: '1',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '1',
      fareId: 'OW_2_20160228',
      originId: '2',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '2',
      fareId: 'OW_1_20160228',
      originId: '2',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '3',
      fareId: 'OW_2_20160228',
      originId: '2',
      routeId: 'Bu-16APR',
    },
    {
      containsId: undefined,
      destinationId: '4',
      fareId: 'OW_3_20160228',
      originId: '2',
      routeId: 'Bu-16APR',
    },
  ]);

  expect(schedule.routes).toEqual({
    'Bu-16APR': {
      agencyId: undefined,
      color: 'E31837',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      desc: undefined,
      id: 'Bu-16APR',
      longName: 'Baby Bullet',
      networkId: undefined,
      shortName: undefined,
      sortOrder: undefined,
      textColor: undefined,
      type: 2,
      url: undefined,
    },
    'Li-16APR': {
      agencyId: undefined,
      color: 'FEF0B5',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      desc: undefined,
      id: 'Li-16APR',
      longName: 'Limited',
      networkId: undefined,
      shortName: undefined,
      sortOrder: undefined,
      textColor: undefined,
      type: 2,
      url: undefined,
    },
    'Lo-16APR': {
      agencyId: undefined,
      color: 'FFFFFF',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      desc: undefined,
      id: 'Lo-16APR',
      longName: 'Local',
      networkId: undefined,
      shortName: undefined,
      sortOrder: undefined,
      textColor: undefined,
      type: 2,
      url: undefined,
    },
    'TaSj-16APR': {
      agencyId: undefined,
      color: '41AD49',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      desc: undefined,
      id: 'TaSj-16APR',
      longName: 'Tamien / San Jose Diridon Caltrain Shuttle',
      networkId: undefined,
      shortName: undefined,
      sortOrder: undefined,
      textColor: undefined,
      type: 3,
      url: undefined,
    },
  });

  expect(Object.keys(schedule.shapes ?? {}).length).toEqual(8);
  expect(
    Object.values(schedule.shapes ?? {}).map((v) => {
      return v.properties;
    }),
  ).toEqual([
    { id: 'cal_sf_gil' },
    { id: 'cal_gil_sf' },
    { id: 'cal_sf_tam' },
    { id: 'cal_tam_sf' },
    { id: 'cal_sf_sj' },
    { id: 'cal_sj_sf' },
    { id: 'cal_tam_sj' },
    { id: 'cal_sj_tam' },
  ]);

  expect(schedule.stopTimes.length).toEqual(3103);
  expect(schedule.stopTimes.slice(0, 10)).toEqual([
    {
      arrivalTime: '7:33:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '7:33:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777403',
      stopSequence: 1,
      timepoint: undefined,
      tripId: '23a',
    },
    {
      arrivalTime: '7:45:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '7:45:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777402',
      stopSequence: 2,
      timepoint: undefined,
      tripId: '23a',
    },
    {
      arrivalTime: '8:33:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '8:33:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777403',
      stopSequence: 1,
      timepoint: undefined,
      tripId: '25a',
    },
    {
      arrivalTime: '8:45:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '8:45:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777402',
      stopSequence: 2,
      timepoint: undefined,
      tripId: '25a',
    },
    {
      arrivalTime: '9:33:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '9:33:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777403',
      stopSequence: 1,
      timepoint: undefined,
      tripId: '27a',
    },
    {
      arrivalTime: '9:45:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '9:45:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777402',
      stopSequence: 2,
      timepoint: undefined,
      tripId: '27a',
    },
    {
      arrivalTime: '10:10:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '10:10:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777403',
      stopSequence: 1,
      timepoint: undefined,
      tripId: '01a',
    },
    {
      arrivalTime: '10:22:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '10:22:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777402',
      stopSequence: 2,
      timepoint: undefined,
      tripId: '01a',
    },
    {
      arrivalTime: '10:33:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '10:33:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777403',
      stopSequence: 1,
      timepoint: undefined,
      tripId: '29a',
    },
    {
      arrivalTime: '10:45:00',
      continuousDropOff: undefined,
      continuousPickup: undefined,
      departureTime: '10:45:00',
      dropOffBookingRuleId: undefined,
      dropOffType: 0,
      endPickupDropOffWindow: undefined,
      locationGroupId: undefined,
      locationId: undefined,
      pickupBookingRuleId: undefined,
      pickupType: 0,
      shapeDistTraveled: undefined,
      startPickupDropOffWindow: undefined,
      stopHeadsign: undefined,
      stopId: '777402',
      stopSequence: 2,
      timepoint: undefined,
      tripId: '29a',
    },
  ]);

  expect(schedule.stops).toEqual({
    '70011': {
      code: '70011',
      desc: undefined,
      id: '70011',
      lat: 37.77639,
      levelId: undefined,
      locationType: 0,
      lon: -122.394992,
      name: 'San Francisco Caltrain',
      parentStation: 'ctsf',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanfranciscostation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70012': {
      code: '70012',
      desc: undefined,
      id: '70012',
      lat: 37.776348,
      levelId: undefined,
      locationType: 0,
      lon: -122.394935,
      name: 'San Francisco Caltrain',
      parentStation: 'ctsf',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanfranciscostation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70021': {
      code: '70021',
      desc: undefined,
      id: '70021',
      lat: 37.757599,
      levelId: undefined,
      locationType: 0,
      lon: -122.39188,
      name: '22nd St Caltrain',
      parentStation: 'ct22',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/22ndstreetstation.html',
      wheelchairBoarding: 2,
      zoneId: '1',
    },
    '70022': {
      code: '70022',
      desc: undefined,
      id: '70022',
      lat: 37.757583,
      levelId: undefined,
      locationType: 0,
      lon: -122.392404,
      name: '22nd St Caltrain',
      parentStation: 'ct22',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/22ndstreetstation.html',
      wheelchairBoarding: 2,
      zoneId: '1',
    },
    '70031': {
      code: '70031',
      desc: undefined,
      id: '70031',
      lat: 37.709537,
      levelId: undefined,
      locationType: 0,
      lon: -122.401586,
      name: 'Bayshore Caltrain',
      parentStation: 'ctba',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/bayshorestation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70032': {
      code: '70032',
      desc: undefined,
      id: '70032',
      lat: 37.709544,
      levelId: undefined,
      locationType: 0,
      lon: -122.40198,
      name: 'Bayshore Caltrain',
      parentStation: 'ctba',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/bayshorestation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70041': {
      code: '70041',
      desc: undefined,
      id: '70041',
      lat: 37.65589,
      levelId: undefined,
      locationType: 0,
      lon: -122.40487,
      name: 'So. San Francisco Caltrain Station',
      parentStation: 'ctssf',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/southsanfranciscostation.html',
      wheelchairBoarding: 2,
      zoneId: '1',
    },
    '70042': {
      code: '70042',
      desc: undefined,
      id: '70042',
      lat: 37.655946,
      levelId: undefined,
      locationType: 0,
      lon: -122.405018,
      name: 'So. San Francisco Caltrain Station',
      parentStation: 'ctssf',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/southsanfranciscostation.html',
      wheelchairBoarding: 2,
      zoneId: '1',
    },
    '70051': {
      code: '70051',
      desc: undefined,
      id: '70051',
      lat: 37.631128,
      levelId: undefined,
      locationType: 0,
      lon: -122.411968,
      name: 'San Bruno Caltrain',
      parentStation: 'ctsb',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanbrunostation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70052': {
      code: '70052',
      desc: undefined,
      id: '70052',
      lat: 37.631108,
      levelId: undefined,
      locationType: 0,
      lon: -122.412076,
      name: 'San Bruno Caltrain',
      parentStation: 'ctsb',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanbrunostation.html',
      wheelchairBoarding: 1,
      zoneId: '1',
    },
    '70061': {
      code: '70061',
      desc: undefined,
      id: '70061',
      lat: 37.59988,
      levelId: undefined,
      locationType: 0,
      lon: -122.386647,
      name: 'Millbrae Caltrain',
      parentStation: 'ctmi',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/millbraetransitcenter.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70062': {
      code: '70062',
      desc: undefined,
      id: '70062',
      lat: 37.599797,
      levelId: undefined,
      locationType: 0,
      lon: -122.386832,
      name: 'Millbrae Caltrain',
      parentStation: 'ctmi',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/millbraetransitcenter.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70071': {
      code: '70071',
      desc: undefined,
      id: '70071',
      lat: 37.58764,
      levelId: undefined,
      locationType: 0,
      lon: -122.36265,
      name: 'Broadway Caltrain',
      parentStation: 'ctbr',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/broadwaystation.html',
      wheelchairBoarding: 2,
      zoneId: '2',
    },
    '70072': {
      code: '70072',
      desc: undefined,
      id: '70072',
      lat: 37.587552,
      levelId: undefined,
      locationType: 0,
      lon: -122.362708,
      name: 'Broadway Caltrain',
      parentStation: 'ctbr',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/broadwaystation.html',
      wheelchairBoarding: 2,
      zoneId: '2',
    },
    '70081': {
      code: '70081',
      desc: undefined,
      id: '70081',
      lat: 37.580197,
      levelId: undefined,
      locationType: 0,
      lon: -122.3449,
      name: 'Burlingame Caltrain',
      parentStation: 'ctbu',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/burlingamestation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70082': {
      code: '70082',
      desc: undefined,
      id: '70082',
      lat: 37.580186,
      levelId: undefined,
      locationType: 0,
      lon: -122.345075,
      name: 'Burlingame Caltrain',
      parentStation: 'ctbu',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/burlingamestation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70091': {
      code: '70091',
      desc: undefined,
      id: '70091',
      lat: 37.568087,
      levelId: undefined,
      locationType: 0,
      lon: -122.323851,
      name: 'San Mateo Caltrain',
      parentStation: 'ctsmat',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmateostation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70092': {
      code: '70092',
      desc: undefined,
      id: '70092',
      lat: 37.568294,
      levelId: undefined,
      locationType: 0,
      lon: -122.324092,
      name: 'San Mateo Caltrain',
      parentStation: 'ctsmat',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmateostation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70101': {
      code: '70101',
      desc: undefined,
      id: '70101',
      lat: 37.552938,
      levelId: undefined,
      locationType: 0,
      lon: -122.309338,
      name: 'Hayward Park Caltrain',
      parentStation: 'ctha',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/haywardparkstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70102': {
      code: '70102',
      desc: undefined,
      id: '70102',
      lat: 37.552994,
      levelId: undefined,
      locationType: 0,
      lon: -122.309608,
      name: 'Hayward Park Caltrain',
      parentStation: 'ctha',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/haywardparkstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70111': {
      code: '70111',
      desc: undefined,
      id: '70111',
      lat: 37.537868,
      levelId: undefined,
      locationType: 0,
      lon: -122.297349,
      name: 'Hillsdale Caltrain',
      parentStation: 'cthi',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/hillsdalestation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70112': {
      code: '70112',
      desc: undefined,
      id: '70112',
      lat: 37.537814,
      levelId: undefined,
      locationType: 0,
      lon: -122.297461,
      name: 'Hillsdale Caltrain',
      parentStation: 'cthi',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/hillsdalestation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70121': {
      code: '70121',
      desc: undefined,
      id: '70121',
      lat: 37.52089,
      levelId: undefined,
      locationType: 0,
      lon: -122.275738,
      name: 'Belmont Caltrain',
      parentStation: 'ctbe',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/belmontstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70122': {
      code: '70122',
      desc: undefined,
      id: '70122',
      lat: 37.520844,
      levelId: undefined,
      locationType: 0,
      lon: -122.275816,
      name: 'Belmont Caltrain',
      parentStation: 'ctbe',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/belmontstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70131': {
      code: '70131',
      desc: undefined,
      id: '70131',
      lat: 37.50805,
      levelId: undefined,
      locationType: 0,
      lon: -122.26015,
      name: 'San Carlos Caltrain',
      parentStation: 'ctsc',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sancarlosstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70132': {
      code: '70132',
      desc: undefined,
      id: '70132',
      lat: 37.507933,
      levelId: undefined,
      locationType: 0,
      lon: -122.260266,
      name: 'San Carlos Caltrain',
      parentStation: 'ctsc',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sancarlosstation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70141': {
      code: '70141',
      desc: undefined,
      id: '70141',
      lat: 37.486159,
      levelId: undefined,
      locationType: 0,
      lon: -122.231936,
      name: 'Redwood City Caltrain',
      parentStation: 'ctrwc',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/redwoodcitystation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70142': {
      code: '70142',
      desc: undefined,
      id: '70142',
      lat: 37.486101,
      levelId: undefined,
      locationType: 0,
      lon: -122.232,
      name: 'Redwood City Caltrain',
      parentStation: 'ctrwc',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/redwoodcitystation.html',
      wheelchairBoarding: 1,
      zoneId: '2',
    },
    '70151': {
      code: '70151',
      desc: undefined,
      id: '70151',
      lat: 37.464645,
      levelId: undefined,
      locationType: 0,
      lon: -122.19779,
      name: 'Atherton Caltrain',
      parentStation: 'ctat',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/athertonstation.html',
      wheelchairBoarding: 2,
      zoneId: '3',
    },
    '70152': {
      code: '70152',
      desc: undefined,
      id: '70152',
      lat: 37.464584,
      levelId: undefined,
      locationType: 0,
      lon: -122.197869,
      name: 'Atherton Caltrain',
      parentStation: 'ctat',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/athertonstation.html',
      wheelchairBoarding: 2,
      zoneId: '3',
    },
    '70161': {
      code: '70161',
      desc: undefined,
      id: '70161',
      lat: 37.454856,
      levelId: undefined,
      locationType: 0,
      lon: -122.182297,
      name: 'Menlo Park Caltrain',
      parentStation: 'ctmp',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/menloparkstation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70162': {
      code: '70162',
      desc: undefined,
      id: '70162',
      lat: 37.454745,
      levelId: undefined,
      locationType: 0,
      lon: -122.182405,
      name: 'Menlo Park Caltrain',
      parentStation: 'ctmp',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/menloparkstation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70171': {
      code: '70171',
      desc: undefined,
      id: '70171',
      lat: 37.443475,
      levelId: undefined,
      locationType: 0,
      lon: -122.164614,
      name: 'Palo Alto Caltrain',
      parentStation: 'ctpa',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/paloaltostation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70172': {
      code: '70172',
      desc: undefined,
      id: '70172',
      lat: 37.443405,
      levelId: undefined,
      locationType: 0,
      lon: -122.164697,
      name: 'Palo Alto Caltrain',
      parentStation: 'ctpa',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/paloaltostation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70191': {
      code: '70191',
      desc: undefined,
      id: '70191',
      lat: 37.429365,
      levelId: undefined,
      locationType: 0,
      lon: -122.141927,
      name: 'California Ave Caltrain',
      parentStation: 'ctca',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/californiaavenuestation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70192': {
      code: '70192',
      desc: undefined,
      id: '70192',
      lat: 37.429333,
      levelId: undefined,
      locationType: 0,
      lon: -122.141978,
      name: 'California Ave Caltrain',
      parentStation: 'ctca',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/californiaavenuestation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70201': {
      code: '70201',
      desc: undefined,
      id: '70201',
      lat: 37.407323,
      levelId: undefined,
      locationType: 0,
      lon: -122.107069,
      name: 'San Antonio Caltrain',
      parentStation: 'ctsa',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanantoniostation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70202': {
      code: '70202',
      desc: undefined,
      id: '70202',
      lat: 37.407277,
      levelId: undefined,
      locationType: 0,
      lon: -122.107125,
      name: 'San Antonio Caltrain',
      parentStation: 'ctsa',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanantoniostation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70211': {
      code: '70211',
      desc: undefined,
      id: '70211',
      lat: 37.394459,
      levelId: undefined,
      locationType: 0,
      lon: -122.075956,
      name: 'Mt View Caltrain',
      parentStation: 'ctmv',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/mountainviewstation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70212': {
      code: '70212',
      desc: undefined,
      id: '70212',
      lat: 37.394402,
      levelId: undefined,
      locationType: 0,
      lon: -122.075994,
      name: 'Mt View Caltrain',
      parentStation: 'ctmv',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/mountainviewstation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70221': {
      code: '70221',
      desc: undefined,
      id: '70221',
      lat: 37.378916,
      levelId: undefined,
      locationType: 0,
      lon: -122.031372,
      name: 'Sunnyvale Caltrain',
      parentStation: 'ctsu',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sunnyvalestation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70222': {
      code: '70222',
      desc: undefined,
      id: '70222',
      lat: 37.378789,
      levelId: undefined,
      locationType: 0,
      lon: -122.031423,
      name: 'Sunnyvale Caltrain',
      parentStation: 'ctsu',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sunnyvalestation.html',
      wheelchairBoarding: 1,
      zoneId: '3',
    },
    '70231': {
      code: '70231',
      desc: undefined,
      id: '70231',
      lat: 37.370598,
      levelId: undefined,
      locationType: 0,
      lon: -121.997114,
      name: 'Lawrence Caltrain',
      parentStation: 'ctla',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/lawrencestation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70232': {
      code: '70232',
      desc: undefined,
      id: '70232',
      lat: 37.370484,
      levelId: undefined,
      locationType: 0,
      lon: -121.997135,
      name: 'Lawrence Caltrain',
      parentStation: 'ctla',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/lawrencestation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70241': {
      code: '70241',
      desc: undefined,
      id: '70241',
      lat: 37.353238,
      levelId: undefined,
      locationType: 0,
      lon: -121.93608,
      name: 'Santa Clara Caltrain',
      parentStation: 'ctscl',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/santaclarastation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70242': {
      code: '70242',
      desc: undefined,
      id: '70242',
      lat: 37.353189,
      levelId: undefined,
      locationType: 0,
      lon: -121.936135,
      name: 'Santa Clara Caltrain',
      parentStation: 'ctscl',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/santaclarastation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70251': {
      code: '70251',
      desc: undefined,
      id: '70251',
      lat: 37.342384,
      levelId: undefined,
      locationType: 0,
      lon: -121.9146,
      name: 'College Park Caltrain',
      parentStation: 'ctco',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/collegeparkstation.html',
      wheelchairBoarding: 2,
      zoneId: '4',
    },
    '70252': {
      code: '70252',
      desc: undefined,
      id: '70252',
      lat: 37.342338,
      levelId: undefined,
      locationType: 0,
      lon: -121.914677,
      name: 'College Park Caltrain',
      parentStation: 'ctco',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/collegeparkstation.html',
      wheelchairBoarding: 2,
      zoneId: '4',
    },
    '70261': {
      code: '70261',
      desc: undefined,
      id: '70261',
      lat: 37.329239,
      levelId: undefined,
      locationType: 0,
      lon: -121.903011,
      name: 'San Jose Diridon Caltrain',
      parentStation: 'ctsj',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanjosediridonstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70262': {
      code: '70262',
      desc: undefined,
      id: '70262',
      lat: 37.329231,
      levelId: undefined,
      locationType: 0,
      lon: -121.903173,
      name: 'San Jose Diridon Caltrain',
      parentStation: 'ctsj',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanjosediridonstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70271': {
      code: '70271',
      desc: undefined,
      id: '70271',
      lat: 37.31174,
      levelId: undefined,
      locationType: 0,
      lon: -121.883721,
      name: 'Tamien Caltrain',
      parentStation: 'ctta',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/tamienstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70272': {
      code: '70272',
      desc: undefined,
      id: '70272',
      lat: 37.31175,
      levelId: undefined,
      locationType: 0,
      lon: -121.883999,
      name: 'Tamien Caltrain',
      parentStation: 'ctta',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/tamienstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '70281': {
      code: '70281',
      desc: undefined,
      id: '70281',
      lat: 37.284102,
      levelId: undefined,
      locationType: 0,
      lon: -121.841955,
      name: 'Capitol Caltrain',
      parentStation: 'ctcap',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/capitolstation.html',
      wheelchairBoarding: 1,
      zoneId: '5',
    },
    '70282': {
      code: '70282',
      desc: undefined,
      id: '70282',
      lat: 37.284062,
      levelId: undefined,
      locationType: 0,
      lon: -121.842037,
      name: 'Capitol Caltrain',
      parentStation: 'ctcap',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/capitolstation.html',
      wheelchairBoarding: 1,
      zoneId: '5',
    },
    '70291': {
      code: '70291',
      desc: undefined,
      id: '70291',
      lat: 37.252422,
      levelId: undefined,
      locationType: 0,
      lon: -121.797643,
      name: 'Blossom Hill Caltrain',
      parentStation: 'ctbl',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/blossomhillstation.html',
      wheelchairBoarding: 1,
      zoneId: '5',
    },
    '70292': {
      code: '70292',
      desc: undefined,
      id: '70292',
      lat: 37.252379,
      levelId: undefined,
      locationType: 0,
      lon: -121.797683,
      name: 'Blossom Hill Caltrain',
      parentStation: 'ctbl',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/blossomhillstation.html',
      wheelchairBoarding: 1,
      zoneId: '5',
    },
    '70301': {
      code: '70301',
      desc: undefined,
      id: '70301',
      lat: 37.129363,
      levelId: undefined,
      locationType: 0,
      lon: -121.650244,
      name: 'Morgan Hill Caltrain',
      parentStation: 'ctmh',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/morganhillstation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '70302': {
      code: '70302',
      desc: undefined,
      id: '70302',
      lat: 37.129321,
      levelId: undefined,
      locationType: 0,
      lon: -121.650304,
      name: 'Morgan Hill Caltrain',
      parentStation: 'ctmh',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/morganhillstation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '70311': {
      code: '70311',
      desc: undefined,
      id: '70311',
      lat: 37.085225,
      levelId: undefined,
      locationType: 0,
      lon: -121.610049,
      name: 'San Martin Caltrain',
      parentStation: 'ctsmar',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmartinstation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '70312': {
      code: '70312',
      desc: undefined,
      id: '70312',
      lat: 37.086653,
      levelId: undefined,
      locationType: 0,
      lon: -121.610936,
      name: 'San Martin Caltrain',
      parentStation: 'ctsmar',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmartinstation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '70321': {
      code: '70321',
      desc: undefined,
      id: '70321',
      lat: 37.003538,
      levelId: undefined,
      locationType: 0,
      lon: -121.566088,
      name: 'Gilroy Caltrain',
      parentStation: 'ctgi',
      platformCode: 'NB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/gilroystation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '70322': {
      code: '70322',
      desc: undefined,
      id: '70322',
      lat: 37.003485,
      levelId: undefined,
      locationType: 0,
      lon: -121.566225,
      name: 'Gilroy Caltrain',
      parentStation: 'ctgi',
      platformCode: 'SB',
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/gilroystation.html',
      wheelchairBoarding: 1,
      zoneId: '6',
    },
    '777402': {
      code: '777402',
      desc: undefined,
      id: '777402',
      lat: 37.330196,
      levelId: undefined,
      locationType: 0,
      lon: -121.901985,
      name: 'San Jose Caltrain Station',
      parentStation: 'ctsj',
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanjosediridonstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    '777403': {
      code: '777403',
      desc: undefined,
      id: '777403',
      lat: 37.311638,
      levelId: undefined,
      locationType: 0,
      lon: -121.883403,
      name: 'Tamien Caltrain Station',
      parentStation: 'ctta',
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/tamienstation.html',
      wheelchairBoarding: 1,
      zoneId: '4',
    },
    ct22: {
      code: undefined,
      desc: undefined,
      id: 'ct22',
      lat: 37.757674,
      levelId: undefined,
      locationType: 1,
      lon: -122.392636,
      name: '22nd St Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/22ndstreetstation.html',
      wheelchairBoarding: 2,
      zoneId: undefined,
    },
    ctat: {
      code: undefined,
      desc: undefined,
      id: 'ctat',
      lat: 37.464349,
      levelId: undefined,
      locationType: 1,
      lon: -122.198106,
      name: 'Atherton Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/athertonstation.html',
      wheelchairBoarding: 2,
      zoneId: undefined,
    },
    ctba: {
      code: undefined,
      desc: undefined,
      id: 'ctba',
      lat: 37.709544,
      levelId: undefined,
      locationType: 1,
      lon: -122.401318,
      name: 'Bayshore Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/bayshorestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctbe: {
      code: undefined,
      desc: undefined,
      id: 'ctbe',
      lat: 37.520504,
      levelId: undefined,
      locationType: 1,
      lon: -122.276075,
      name: 'Belmont Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/belmontstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctbl: {
      code: undefined,
      desc: undefined,
      id: 'ctbl',
      lat: 37.252801,
      levelId: undefined,
      locationType: 1,
      lon: -121.797369,
      name: 'Blossom Hill Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/blossomhillstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctbr: {
      code: undefined,
      desc: undefined,
      id: 'ctbr',
      lat: 37.587466,
      levelId: undefined,
      locationType: 1,
      lon: -122.363233,
      name: 'Broadway Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/broadwaystation.html',
      wheelchairBoarding: 2,
      zoneId: undefined,
    },
    ctbu: {
      code: undefined,
      desc: undefined,
      id: 'ctbu',
      lat: 37.579719,
      levelId: undefined,
      locationType: 1,
      lon: -122.345266,
      name: 'Burlingame Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/burlingamestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctca: {
      code: undefined,
      desc: undefined,
      id: 'ctca',
      lat: 37.428835,
      levelId: undefined,
      locationType: 1,
      lon: -122.142703,
      name: 'California Ave Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/californiaavenuestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctcap: {
      code: undefined,
      desc: undefined,
      id: 'ctcap',
      lat: 37.284359,
      levelId: undefined,
      locationType: 1,
      lon: -121.841589,
      name: 'Capitol Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/capitolstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctco: {
      code: undefined,
      desc: undefined,
      id: 'ctco',
      lat: 37.34217,
      levelId: undefined,
      locationType: 1,
      lon: -121.914998,
      name: 'College Park Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/collegeparkstation.html',
      wheelchairBoarding: 2,
      zoneId: undefined,
    },
    ctgi: {
      code: undefined,
      desc: undefined,
      id: 'ctgi',
      lat: 37.003606,
      levelId: undefined,
      locationType: 1,
      lon: -121.566497,
      name: 'Gilroy Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/gilroystation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctha: {
      code: undefined,
      desc: undefined,
      id: 'ctha',
      lat: 37.552346,
      levelId: undefined,
      locationType: 1,
      lon: -122.308916,
      name: 'Hayward Park Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/haywardparkstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    cthi: {
      code: undefined,
      desc: undefined,
      id: 'cthi',
      lat: 37.537503,
      levelId: undefined,
      locationType: 1,
      lon: -122.298001,
      name: 'Hillsdale Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/hillsdalestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctla: {
      code: undefined,
      desc: undefined,
      id: 'ctla',
      lat: 37.370815,
      levelId: undefined,
      locationType: 1,
      lon: -121.997258,
      name: 'Lawrence Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/lawrencestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctmh: {
      code: undefined,
      desc: undefined,
      id: 'ctmh',
      lat: 37.129081,
      levelId: undefined,
      locationType: 1,
      lon: -121.650721,
      name: 'Morgan Hill Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/morganhillstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctmi: {
      code: undefined,
      desc: undefined,
      id: 'ctmi',
      lat: 37.600006,
      levelId: undefined,
      locationType: 1,
      lon: -122.386534,
      name: 'Millbrae Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/millbraetransitcenter.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctmp: {
      code: undefined,
      desc: undefined,
      id: 'ctmp',
      lat: 37.454604,
      levelId: undefined,
      locationType: 1,
      lon: -122.182518,
      name: 'Menlo Park Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/menloparkstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctmv: {
      code: undefined,
      desc: undefined,
      id: 'ctmv',
      lat: 37.393879,
      levelId: undefined,
      locationType: 1,
      lon: -122.076327,
      name: 'Mt View Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/mountainviewstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctpa: {
      code: undefined,
      desc: undefined,
      id: 'ctpa',
      lat: 37.44307,
      levelId: undefined,
      locationType: 1,
      lon: -122.1649,
      name: 'Palo Alto Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/paloaltostation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctrwc: {
      code: undefined,
      desc: undefined,
      id: 'ctrwc',
      lat: 37.485412,
      levelId: undefined,
      locationType: 1,
      lon: -122.231957,
      name: 'Redwood City Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/redwoodcitystation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsa: {
      code: undefined,
      desc: undefined,
      id: 'ctsa',
      lat: 37.407157,
      levelId: undefined,
      locationType: 1,
      lon: -122.107231,
      name: 'San Antonio Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanantoniostation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsb: {
      code: undefined,
      desc: undefined,
      id: 'ctsb',
      lat: 37.631106,
      levelId: undefined,
      locationType: 1,
      lon: -122.412018,
      name: 'San Bruno Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanbrunostation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsc: {
      code: undefined,
      desc: undefined,
      id: 'ctsc',
      lat: 37.507361,
      levelId: undefined,
      locationType: 1,
      lon: -122.260365,
      name: 'San Carlos Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sancarlosstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctscl: {
      code: undefined,
      desc: undefined,
      id: 'ctscl',
      lat: 37.352915,
      levelId: undefined,
      locationType: 1,
      lon: -121.936376,
      name: 'Santa Clara Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/santaclarastation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsf: {
      code: undefined,
      desc: undefined,
      id: 'ctsf',
      lat: 37.776439,
      levelId: undefined,
      locationType: 1,
      lon: -122.394323,
      name: 'San Francisco Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanfranciscostation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsj: {
      code: undefined,
      desc: undefined,
      id: 'ctsj',
      lat: 37.329392,
      levelId: undefined,
      locationType: 1,
      lon: -121.902181,
      name: 'San Jose Diridon Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanjosediridonstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsmar: {
      code: undefined,
      desc: undefined,
      id: 'ctsmar',
      lat: 37.085775,
      levelId: undefined,
      locationType: 1,
      lon: -121.610809,
      name: 'San Martin Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmartinstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctsmat: {
      code: undefined,
      desc: undefined,
      id: 'ctsmat',
      lat: 37.568209,
      levelId: undefined,
      locationType: 1,
      lon: -122.323933,
      name: 'San Mateo Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sanmateostation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctssf: {
      code: undefined,
      desc: undefined,
      id: 'ctssf',
      lat: 37.655852,
      levelId: undefined,
      locationType: 1,
      lon: -122.405429,
      name: 'So. San Francisco Caltrain Station',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/southsanfranciscostation.html',
      wheelchairBoarding: 2,
      zoneId: undefined,
    },
    ctsu: {
      code: undefined,
      desc: undefined,
      id: 'ctsu',
      lat: 37.378427,
      levelId: undefined,
      locationType: 1,
      lon: -122.030742,
      name: 'Sunnyvale Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/sunnyvalestation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
    ctta: {
      code: undefined,
      desc: undefined,
      id: 'ctta',
      lat: 37.31164,
      levelId: undefined,
      locationType: 1,
      lon: -121.8839,
      name: 'Tamien Caltrain',
      parentStation: undefined,
      platformCode: undefined,
      timezone: undefined,
      ttsName: undefined,
      url: 'http://www.caltrain.com/stations/tamienstation.html',
      wheelchairBoarding: 1,
      zoneId: undefined,
    },
  });

  expect(schedule.trips?.length).toEqual(218);
  expect(schedule.trips?.slice(0, 10)).toEqual([
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '23a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '23',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '25a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '25',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '27a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '27',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '01a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '1',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '29a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '29',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '31a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '31',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '33a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '33',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '35a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '35',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '37a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '37',
      wheelchairAccessible: undefined,
    },
    {
      bikesAllowed: undefined,
      blockId: undefined,
      directionId: 0,
      headsign: 'DIRIDON STATION',
      id: '39a',
      routeId: 'TaSj-16APR',
      serviceId: 'CT-16APR-Caltrain-Saturday-02',
      shapeId: 'cal_tam_sj',
      shortName: '39',
      wheelchairAccessible: undefined,
    },
  ]);
});
